### ISSUE TITLE
DNAC: Python module 'requests' not available in fresh Python 3.7 install. Suggest adding install module 'requests' step to doc.

### ISSUE THREAD

**Issue by JoelRiglerIG** [CiscoDevNet/learning-labs-issues#100]
Learning Labs: "Programming the Digital Network Architecture (Cisco DNA)" (https://developer.cisco.com/learning/tracks/programming-dna) 
section: "Introduction to Cisco DNA Center REST APIs", first example program "End to End Visibility and Assurance with Path Trace and Cisco DNA Center Platform":

This section takes the user through creation and running the Python script "path_trace_prep.py" and "path_trace.py".  

Using a freshly installed Python (3.7.3) (on Mac: '$ brew install python3'), creation and activation of a python virtual environment, I attempted to run scripts 'path_trace_prep.py' and 'path_trace.py' per instructions.  Python reports: "ModuleNotFoundError: No module named 'requests' ".  

I suggest adding explicit instruction steps to documentation as how to handle this missing module - or perhaps a reference to how to obtain missing modules in general.  In this case, the Mac OS import command is simply: "pip3 install requests". 

For this environment, once this was done, 'path_trace.py' executed correctly per instructions.

**Comment by klevenstein** [comment]
Addressed, just needs to be published

**Comment by srshalini** [comment]
completed the publish.
