### ISSUE TITLE
Remove mantl-app and mantl-101 from repo and redirect; remove shipped tag

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#103]
These labs are in the repo at https://github.com/CiscoCloud/mantl-devnet-learninglabs. The mantl product itself is end-of-life, so let's remove those two Lab folders from the repo to avoid spurious link checker errors like these:

FILE: ./labs/mantl-101/3.md
[✓] assets/images/cisco-live.jpg

FILE: ./labs/mantl-101/1.md
[✓] https://mantl.io
[✓] assets/images/git-bash.png
[✓] assets/images/virtualbox-empty.png
[✓] assets/images/clone-mantl.png
[✓] assets/images/git-cli-102.png
[✓] assets/images/vagrantfile-notepad.png
[✓] assets/images/vagrant-up.png
[✓] https://vagrantup.com/downloads.html
[✓] assets/images/vagrant-version-error.png
[✓] assets/images/vagrant-virtualbox-progress.png

FILE: ./labs/mantl-101/2.md
[✓] assets/images/cisco-live.jpg

FILE: ./labs/mantl-app/3.md
[✓] https://run.pstmn.io/button.svg
[✓] https://app.getpostman.com/run-collection/c092b5e86a8a258b55a7
[✓] https://hub.docker.com/r/ciscodevnet/mantl-demo/
[✖] https://mantlsandbox.cisco.com/marathon

FILE: ./labs/mantl-app/1.md
[✓] http://getpostman.com
[✖] https://mantlsandbox.cisco.com/ui
[✓] assets/diagram-1.png

FILE: ./labs/mantl-app/2.md
[✓] assets/env_selector.png
[✓] https://run.pstmn.io/button.svg
[✓] https://app.getpostman.com/run-collection/5a9509901ade3e23ff63
[✖] https://mantlsandbox.cisco.com/marathon

FILE: ./labs/mantl-app/4.md
[✖] https://www.ciscoshipped.io
[✓] https://developer.cisco.com/learning/labs/tags/shipped

This removal and redirect should also remove the tag at developer.cisco.com/learning/labs/tags/shipped since shipped is also eol.

**Comment by klevenstein** [comment]
Started to try to fix this, but I need access to the repo: https://github.com/CiscoCloud/mantl-devnet-learninglabs/pull/43
