### ISSUE TITLE
Broken references to images in the IOx-Learning-Labs repo

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#105]
A few remaining posts/files references to images remain in these files.

FILE: ./labs/iot-iox-app-docker/2.md
[✓] https://developer.cisco.com/site/devnet/sandbox/
[✖] /posts/files/iot-iox-app-docker/sandbox-iot.png
[✖] /posts/files/iot-iox-app-docker/sandbox-iot-iox-caf.png
[✖] /posts/files/iot-iox-app-docker/screen-sandbox-reserve-2.png

FILE: ./labs/iot-iox-app/2.md
[✓] https://developer.cisco.com/site/devnet/sandbox/
[✖] /posts/files/iot-iox-app/sandbox-iot.png
[✖] /posts/files/iot-iox-app/sandbox-iot-iox-caf.png
[✖] /posts/files/iot-iox-app/screen-sandbox-reserve-2.png

FILE: ./labs/iot-iox-fd-deploy/2.md
[✖] /posts/files/iot-iox-fd-deploy/assets/images/IOx-Lab-Link.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/IOx-Reservation.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/IOx-Lab-E-mail.png

FILE: ./labs/iot-iox-fd-deploy/3.md
[✖] /posts/files/iot-iox-fd-deploy/assets/images/IOx-After-Reservation-IP-addresses.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/updated_ip_standard.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/Fog-LogIn.png

FILE: ./labs/iot-iox-fd-deploy/4.md
[✖] /posts/files/iot-iox-fd-deploy/assets/images/SelectDeviceTab.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/AddDeviceFD.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/IOxInfoFD.png

FILE: ./labs/iot-iox-fd-deploy/5.md
[✓] https://github.com/CiscoDevNet/iox-docker-python-web
[✖] /posts/files/iot-iox-fd-deploy/assets/images/GithubDownload.png

FILE: ./labs/iot-iox-fd-deploy/6.md
[✖] /posts/files/iot-iox-fd-deploy/assets/images/AddAppButtonFD.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/DockerImageCreate0.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/DockerImageCreate1.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/DockerImageCreate2.png
[✓] https://hub.docker.com/r/ciscodevnet/iox-docker-python-web/
[✓] https://github.com/CiscoDevNet/iox-docker-python-web
[✖] /posts/files/iot-iox-fd-deploy/assets/images/IOxApplicationUnPublished.png

FILE: ./labs/iot-iox-fd-deploy/7.md
[✖] /posts/files/iot-iox-fd-deploy/assets/images/PublishTheUnpublished.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/NowAvailable.png

FILE: ./labs/iot-iox-fd-deploy/8.md
[✖] /posts/files/iot-iox-fd-deploy/assets/images/ClickIOxApp.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/InstallButton.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/SelectDevicesForInstall.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/NextButtonDeploy.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/DoneLetsGo.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/DeploymentProgress.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/DeploymentComplete.png

FILE: ./labs/iot-iox-fd-deploy/9.md
[✖] /posts/files/iot-iox-fd-deploy/assets/images/ApplicationCheck0.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/AppCheck1.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/AppCheck2.png
[✖] /posts/files/iot-iox-fd-deploy/assets/images/AppCheck3.png
[✖] http://ExternalIP:MappedPort/time
[✖] /posts/files/iot-iox-fd-deploy/assets/images/AppCheck4.png

FILE: ./labs/iox-sandbox-reservation/2.md
[✖] /posts/files/iox-sandbox-reservation/assets/images/IOx-Lab-Link.png
[✖] /posts/files/iox-sandbox-reservation/assets/images/IOx-Reservation.png
[✖] /posts/files/iox-sandbox-reservation/assets/images/IOx-Lab-E-mail.png

FILE: ./labs/iox-sandbox-reservation/3.md
[✖] /posts/files/iox-sandbox-reservation/assets/images/updated_ip_standard.png
[✖] /posts/files/iox-sandbox-reservation/assets/images/Fog-LogIn.png
[✖] /posts/files/iox-sandbox-reservation/assets/images/IOx-LogIn.png

FILE: ./labs/street-cred/2.md
[✖] /posts/files/iox-sandbox-reservation/assets/images/IOx-Lab-Link.png
[✖] /posts/files/iox-sandbox-reservation/assets/images/IOx-Reservation.png
[✖] /posts/files/iox-sandbox-reservation/assets/images/IOx-Lab-E-mail.png

FILE: ./labs/street-cred/3.md
[✖] /posts/files/iox-sandbox-reservation/assets/images/updated_ip_standard.png
[✖] /posts/files/iox-sandbox-reservation/assets/images/Fog-LogIn.png
[✖] /posts/files/iox-sandbox-reservation/assets/images/IOx-LogIn.png

Also double-check why these assets/images references are broken:

FILE: ./labs/iox-azure-data-lab/2.md
[✖] assets/images/2018-04-05_17-46-15.png
[✖] assets/images/2018-04-05_17-45-39.png

FILE: ./labs/iox-azure-data-lab/3.md
[✓] https://us.ciscokinetic.io
[✓] mailto:devnet_iot+user10@cisco.com
[✖] assets/images/2018-04-05_17-51-59.png
[✖] assets/images/2018-04-05_22-14-07.png
[✖] assets/images/2018-04-05_22-14-45.png
[✖] assets/images/2018-04-05_22-16-15.png
[✖] assets/images/2018-04-05_22-18-00.png
[✖] assets/images/2018-04-05_22-45-34.png
[✖] assets/images/2018-04-05_22-49-06.png

FILE: ./labs/iox-azure-data-lab/4.md
[✖] assets/images/2018-04-05_23-02-45.png
[✖] assets/images/2018-04-05_23-12-52.png
[✖] assets/images/2018-04-05_23-16-13.png
[✖] assets/images/2018-04-09_10-54-52.png
[✖] assets/images/2018-04-09_10-52-00.png
[✖] assets/images/2018-04-09_10-55-54.png
[✖] assets/images/2018-04-09_11-13-59.png
[✖] assets/images/2018-04-09_11-16-55.png

FILE: ./labs/iox-azure-data-lab/5.md
[✖] assets/images/20180409_094618.jpg
[✖] assets/images/2018-04-09_12-08-16.png

**Comment by klevenstein** [comment]
Most of these should now be fixed. However, I can't do much about the ones with the datestamp filenames in /labs/iox-azure-data-lab/, because those files don't seem to exist. @JockDaRock can you shed any light?

**Comment by annegentle** [comment]
That lab is set to active:false, so it likely wasn't ever published. We can ignore those and I'll close this Issue.
