### ISSUE TITLE
Parsing XML Learning Lab will not work with CMX Sandbox

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#106]
This resource does not appear to be able to provide XML: https://cmxlocationsandbox.cisco.com/api/config/v1/maps/info/DevNetCampus/DevNetBuilding/DevNetZone
If you ask for application/json it works…if you ask for application/xml or text/xml you get the ‘CMX Error’ as the response body.

This prevents this Lab from working: https://developer.cisco.com/learning/lab/coding-201-parsing-xml/step/1

**Comment by annegentle** [comment]
@denapom11 Do you have ideas for a Sandbox that provides XML in responses?

**Comment by annegentle** [comment]
This Sandbox has been removed, so this LL should be hidden until we find a good replacement Sandbox. Have asked the Sandbox team, they're going to look, and also have asked the DA team if they can think of any.

**Comment by annegentle** [comment]
The IOS XE Sandbox returns NETCONF which is XML. Here's an example that can replace the current example in the LL, where the user gets XML back, prints out the XML, then uses an XML parser to pull out the relevant information.

Note that the best Sandbox to use is the "Recommended Code" Sandbox, IOS XE on CSR Recommended Code AlwaysOn at https://devnetsandbox.cisco.com/RM/Diagram/Index/27d9747a-db48-4565-8d44-df318fce37ad?diagramType=Topology.

```
#!/usr/bin/env python

# import the ncclient library
from ncclient import manager
import sys
import xml.dom.minidom


# the variables below assume the user is leveraging the
# always on sandbox.
HOST = 'ios-xe-mgmt.cisco.com'
# use the NETCONF port for your IOS-XE device
PORT = 10000
# use the user credentials for your IOS-XE device
USER = 'developer'
PASS = 'C1sco12345'


# create a main() method
def main():
    """
    Main method that retrieves the hostname from config via NETCONF.
    """
    with manager.connect(host=HOST, port=PORT, username=USER,
                         password=PASS, hostkey_verify=False,
                         device_params={'name': 'default'},
                         allow_agent=False, look_for_keys=False) as m:

        # XML filter to issue with the get operation
        # IOS-XE pre-16.2     YANG model called urn:ios
        # IOS-XE 16.2 - 16.4  YANG model called http://cisco.com/ns/yang/ned/ios
        # IOS-XE 16.5+        YANG model called http://cisco.com/ns/yang/Cisco-IOS-XE-native
        hostname_filter = '''
                          <filter>
                              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                                  <hostname></hostname>
                              </native>
                          </filter>
                          '''
        result = m.get_config('running', hostname_filter)
        print(result)
        xml_doc = xml.dom.minidom.parseString(result.xml)
        hostname = xml_doc.getElementsByTagName("hostname")
        print(hostname[0].firstChild.nodeValue)


if __name__ == '__main__':
    sys.exit(main())

```

**Comment by annegentle** [comment]
I've published the interim to revise as an example rather than including the URL that does not work.

**Comment by annegentle** [comment]
Another XML-returning Sandbox is the ACI Sandbox. Using the ACI sandbox, we can get back queries in either JSON or XML depending on the file-type we append in the URL of the API call.
For example, https://apic/api/some/class/or/mo.{json|xml}. I'm not sure which one is simpler, but the Python example above works for the IOS XE Sandbox so we may want to start with that.

**Comment by qsnyder** [comment]
@annegentle -- Let me know if there's something you'd like me to work up with an ACI example at some point.  I'm good with whatever the group chooses, just wanted to offer services.

**Comment by annegentle** [comment]
I'd love that @qsnyder! In my mind, ACI could be slightly preferable to fit with the flow and comparison of JSON and XML, and the managed object data model makes sense. Please do write up an ACI example, that would be great.

**Comment by annegentle** [comment]
One more note to say, the Learning Lab content is in https://github.com/CiscoDevNet/coding-series-learning-labs

**Comment by qsnyder** [comment]
Perfect.  I'll start work on that.
Would it be a fair assumption that the goal is to refresh both 201 and 202 for consistency against the APIs -- or just rewrite 201?

**Comment by annegentle** [comment]
Good question - yes, please revise 202 also. I like that we can use one API for both examples, ACI
 is especially good for this since the data formats are parallel.

And just more input for the 101, 201, naming, we have had requests from the field to stop using the 101, 201 naming (because we're not a university, no one really knows what level that is, and so on). So for now, the "coding-101" LabID now redirects to another Lab, [What are REST APIs?](https://developer.cisco.com/learning/labs/what-are-rest-apis/step/1). And the 203, 204, and upwards have been deactivated. So can you also remove 201 and 202 from the title? We don't need to change the URL. And I guess that also means removing a lot of related Lab IDs from the JSON. Not to make it more complex, but just that the files can be cleaned up too.

**Comment by qsnyder** [comment]
Submitted a PR to 201, 202 -- rewriting against ACI AO sandbox.  Both labs have same eventual outcome (query fabric against tenant class, returning health as wel).  Gives nice nested XML and JSON to parse through multiple levels.  Rewrote code examples to align.
