### ISSUE TITLE
Add titles to sidebar TOC in https://developer.cisco.com/learning/modules/intermediate-aci-prog/sbx-intermediate-aci-01_aci-api/step/1

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#107]
Update the JSON file for page titles for Lab ID sbx-intermediate-aci-01_aci-api. Update for the whole repo if other Labs within the repo do not have titles in the JSON file.

**Comment by klevenstein** [comment]
The whole lab could probably use an overall style edit, but that's another issue for another day.

**Comment by movinalot** [comment]
I have added Sidebar TOC page titles as part of the python3 update
