### ISSUE TITLE
Broken links in labs-cloud-collab

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#109]
Looks like the HowdyAI repo has some reorganization that affects our links. Here are the affected files and broken links indicated with an X:

FILE: ./labs/collab-spark-botkit/1.md
[✓] https://github.com/howdyai/Botkit
[✓] https://github.com/CiscoDevNet/botkit-webex-samples/blob/master/convos/skills/convo-activities.js
[✓] assets/images/Intro_activities_chat.png
[✓] https://www.webex.com/products/teams/index.html
[✓] https://botkit.ai/docs/
[✖] https://github.com/howdyai/Botkit/blob/master/docs/readme.md
[✓] https://botkit.ai/docs/readme-webex.html
[✓] https://github.com/howdyai/Botkit-starter-ciscospark
[✓] https://botkit.ai/docs/middleware.html

FILE: ./labs/collab-spark-botkit/8.md
[✖] https://github.com/howdyai/Botkit/blob/master/docs/readme.md#conversation-threads
[✓] https://github.com/CiscoDevNet/botkit-webex-samples/blob/master/learninglab/skills/variables.js#L33
[✓] assets/images/Step7_variables_chat.png
[✓] https://botkit.ai/docs/core.html
[✓] https://github.com/CiscoDevNet/botkit-webex-samples
[✓] https://github.com/CiscoDevNet/botkit-webex-samples/blob/master/convos/skills/convo-quiz.js#L7
[✓] https://github.com/CiscoDevNet/botkit-webex-samples/blob/master/convos/skills/convo-quiz.js#L18
[✓] https://developer.cisco.com/learning/tracks/collab-cloud/spark-apps/collab-spark-bot-hosting/step/1

One more broken link doesn't appear to have a replacement, going to this repo: https://github.com/spark3dp/spark-js-SDK also doesn't show any replacement site. Probably need to revise the lab to not point to that SDK.

FILE: ./labs/collab-spark-intl/2.md
[✓] https://developer.webex.com
[✓] https://developer.webex.com/my-apps/new
[✓] assets/images/step2-new-app.png
[✓] http://bit.ly/SparkIntegration-512x512
[✓] assets/images/step2-scopes.png
[✓] https://github.com/CiscoDevNet/webex-integration-sample/blob/master/server.js#L30
[✓] assets/images/step2-client-id-secret.png
[✖] https://webex.github.io/spark-js-sdk/guides/browsers/
[✓] https://github.com/CiscoDevNet/webex-integration-sample/blob/master/server.js#L40

**Comment by ObjectIsAdvantag** [comment]
I did not even know that project existed: https://github.com/spark3dp/spark-js-SDK
last commit was in 2015!

this is certainly the SDK we want to point to: https://github.com/webex/webex-js-sdk

**Comment by ObjectIsAdvantag** [comment]
@annegentle due to the Botkit update a month 1/2 ago, there may be more to update, we'll need someone to go thru the whole lab, and code samples and update accordingly.

short term: let's continue using the previous version of Botkit by pointing to it explicitely in our code samples.

**Comment by annegentle** [comment]
I think you can use https://webex.github.io/webex-js-sdk/guides/browsers/ for the last missing link.

**Comment by dethanga** [comment]
> I think you can use https://webex.github.io/webex-js-sdk/guides/browsers/ for the last missing link.

Thanks so much Anne!

**Comment by dethanga** [comment]
Hi @annegentle and @klevenstein 

I have verified the updated links. All works fine in staging. Published to production.
Hence I am closing this issue.

Regards,
Devi
