### ISSUE TITLE
Need to correct title in https://developer.cisco.com/learning/lab/dnac-basic/step/1 (but can't find the Lab ID?)

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#110]
The title of one of the pages on https://developer.cisco.com/learning/lab/dnac-basic/step/1ccontains DNAC and this should be changed to Cisco DNA Center. I couldn't find the Lab ID on first search though so need some help triaging the fix.

**Comment by klevenstein** [comment]
It looks like it's the labs here:
https://github.com/CiscoDevNet/dnac-learning-labs

Descriptions indicate that these labs should be deprecated - shall we un-publish?

**Comment by annegentle** [comment]
Oh, yes - those JSON files should have `redirectTo` added for each Lab. They have to be set to "active" for the redirectTo to work.

**Comment by annegentle** [comment]
Well, it gets more tangled... looking at the release history on the archived repo dnac-learning-labs (https://github.com/CiscoDevNet/dnac-learning-labs/releases), I had already changed these lab IDs to use the newer labs. I'll republish from intro-dnac-labs and see if that helps.

**Comment by annegentle** [comment]
Ok, I think that the original problem is fixed... redirected dnac-basic to an overview Lab.
