### ISSUE TITLE
Docker instructions for running code against Devnet Learning Lab

### ISSUE THREAD

**Issue by RunSi** [CiscoDevNet/learning-labs-issues#111]
The Learning Lab provides instruction for running the code in a Docker Container.
I notice that the Docker Build file has an Entrypoint of
>ENTRYPOINT ["ansible-playbook", "site.yml"]

This results in any built image immediately running the site.yml playbook and then closing, thus no interactivity in order to follow lab.  I would suggest removal of the Entrypoint and the following command to run the container
```
docker run --rm -it --mount source="$(pwd)/code",target=/home/devnet,type=bind ansible_sdwan /bin/bash
```

**Comment by annegentle** [comment]
Thanks Simon, moving to the Learning Labs Issues repo to triage and assign. Appreciate it!

**Comment by annegentle** [comment]
To triage I did some testing and can see why removing ENTRYPOINT from the `Dockerfile` makes sense here. Then I tried testing and running `docker run --rm -it --mount source="$(pwd)/code",target=/home/devnet,type=bind ansible_sdwan /bin/bash` with the newly-built Docker image, and cannot ping the Sandbox (10.10.20.90). I tried ping after:

```
[root@5d87fc64f2ca devnet]# ansible-playbook site.yml -i inventories/inventory.yml -t lab1:login
```
and getting:
```
TASK [login : Login to the vManage] ************************************************************************************************
fatal: [vManage]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error timed out>", "redirected": false, "status": -1, "url": "https://10.10.20.90:8443/dataservice/j_security_check"}
```
From a local Ansible client, I could successfully log in to lab1 when running the playbook with the parameters. 

I think the best course of action is to remove the Docker mention from the byod.html file entirely, as it is too hard to document both ways (Docker and non-Docker) in the rest of the Lab.

**Comment by vvaliapa** [comment]
I have removed the "Run from Docker" section in the byod.html files in this module:  https://developer.cisco.com/learning/modules/cisco_sd-wan_with_ansible
 Closing this issue.
