### ISSUE TITLE
Need Page title correction, editorial review, and username updates in the "sdwan-automation-dayone-config" lab.

### ISSUE THREAD

**Issue by vvaliapa** [CiscoDevNet/learning-labs-issues#115]
1. Change the first page heading from "SD-WAN Day One automation with Ansible" to "Introduction" to match with the JSON.
2. Give link for "Building SD-WAN Topologies in VIRL" learning lab in relevant sections.
3. Check for the comments regarding the username in the https://cisco.app.box.com/notes/504590831106
4. Do an editorial review

**Comment by vvaliapa** [comment]
Successfully tested the lab. Updated the title mismatch, updated link to the "Building SD-WAN Topologies in VIRL" Lab and done the editorial review.
Here is the link: https://developer.cisco.com/learning/lab/sdwan-automation-dayone-config/step/1

**Comment by annegentle** [comment]
Fixed; closing.
