### ISSUE TITLE
The Page Description is Missing for ckc101 Learning Lab in the JSON file

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#117]
Following URL, https://developer.cisco.com/learning/tracks/iot/cdp/ckc101/step/1

The page description needs to be updated

<img width="862" alt="003" src="https://user-images.githubusercontent.com/50714/63282787-35239f80-c275-11e9-80d7-99c41ca2a103.PNG">

Request for more information about using Postman

**Comment by annegentle** [comment]
This Lab has been retired, closing Issue.
