### ISSUE TITLE
Need Page title correction, editorial review, and username updates in the "sdwan-automation-virl-topologies" lab

### ISSUE THREAD

**Issue by vvaliapa** [CiscoDevNet/learning-labs-issues#118]
1.Need to change the first-page title from "Building SD-WAN topologies in VIRL" to "Introduction"
2. Check for the comments regarding the username in the 
    https://cisco.app.box.com/notes/504590831106 and update accordingly.
3. Do an editorial review.

**Comment by vvaliapa** [comment]
Tested "sdwan-automation-virl-topologies" Lab and edited the content accordingly. Also corrected the title mismatch, editing, and formatting issues and published in the production server.
Here is the link: https://developer.cisco.com/learning/lab/sdwan-automation-virl-topologies/step/2

**Comment by annegentle** [comment]
Fixed; closing.
