### ISSUE TITLE
NSO-labs Cisco IT 101 to 104; content verification and editorial fixes 

### ISSUE THREAD

**Issue by dethanga** [CiscoDevNet/learning-labs-issues#119]
Doing complete content review and correcting the typos, formatting issues. 
Queries are posted in the Box note: https://cisco.app.box.com/notes/504590831106

**Comment by annegentle** [comment]
@smupad Can you take a look at the questions in the Box note? My guess is that those user names will not be changed, but want to have you take a look and confirm.

**Comment by smupad** [comment]
> @smupad Can you take a look at the questions in the Box note? My guess is that those user names will not be changed, but want to have you take a look and confirm.

@dethanga @annegentle - I have taken a look at the NSO lab questions and responded in Box note. I will continue reviewing the rest of the observations.

**Comment by annegentle** [comment]
I think this Issue can be closed as no user names need to be changed.

**Comment by dethanga** [comment]
@annegentle 

Yes, I checked the comments provided by Smita in the Box notes. No user name updates for NSO.
Hence I am closing this issue. Thanks - Devi
