### ISSUE TITLE
No longer using root user in Vagrant Learning Lab plus instructions update

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#122]
https://developer.cisco.com/learning/modules/vagrant_up/vagrant_101/step/2 uses root@devbox in the examples, but it should be developer@devbox.

**Comment by annegentle** [comment]
Learning Lab should use `developer` username (and password), plus rewrite the LL so that user knows that the devbox will not need to go external to find the right image files.

**Comment by annegentle** [comment]
Here are the results of running `vagrant init` followed by `vagrant box list` - which does show `hashicorp/precise64 (virtualbox, 1.1.0`).

However, seems like the system still wants to download something. We will triage further with the sandbox team.


```
[developer@devbox vagrant_explore]$ vagrant box list
hashicorp/precise64 (virtualbox, 1.1.0)
[developer@devbox vagrant_explore]$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hashicorpprecise64' could not be found. Attempting to find and instal
l...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'hashicorpprecise64' (v0) for provider: virtualbox
    default: Downloading: hashicorpprecise64
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/developer/coding/vagrant_explore/hashicorpprecise64
```

**Comment by annegentle** [comment]
Vibhinna was able to bring the vagrant box up, so she is updating the Learning Lab with the new text the person will see in return (which does contain an error about not being able to update the image but lets the person continue).

**Comment by vvaliapa** [comment]
I have tested this lab using DevBox sandbox under DevNet and updated the username as developer in all commands and sample outputs. Also added note for “Vagrant Up” and “Vagrant reload” command. Smita wants to test the Lab using “Devbox Github Access” sandbox  under “RA_External_Development”. Karin will be testing this lab with the “Devbox Github Access” sandbox.

**Comment by klevenstein** [comment]
Fixed and published, closing
