### ISSUE TITLE
Perform content verification and check for the title mismatch for intro-to-genie, intro-to-pyats, Parsers with Genie, Genie PTS using Robot, and Triggers and Verifications with Genie labs.

### ISSUE THREAD

**Issue by vvaliapa** [CiscoDevNet/learning-labs-issues#127]
Review the pyATS learning lab contents for grammatical errors, logical flow, title mismatch, and update accordingly.

**Comment by klevenstein** [comment]
Some items I wasn't sure how to fix:

1. In /labs/intro-to-genie/5.md:
`1. Navigate to the folder above and view the HTML log files using any browser. The logs contain step-by-step execution details of each test case that was run:`
How do you get your browser to access these files? 

2. In /labs/parsers-with-genie/2.md, ouput after the command `robot genie_connect.robot` includes this error:
`./pyats/lib/python3.6/site-packages/unicon/plugins/nxos/bases.py:22: DeprecationWarning: Arguments 'username', 'enable_password','tacacs_password' and 'line_password' are now deprecated and replaced by 'credentials'.
  super().__init__(*args, **kwargs)`

3. Failed tests after `robot genie_parsers.robot`:
```execute and parse 'show bgp process vrf all' on UUT                   | FAIL |
Could not find parser for 'genie.libs.parser.show_bgp.ShowBgpProcessVrfAll'
------------------------------------------------------------------------------
execute and parse 'show platform' on UUT                              | FAIL |
Could not find parser for 'genie.libs.parser.show_platform.ShowModule'
------------------------------------------------------------------------------
Genie Parsers                                                         | FAIL |
3 critical tests, 1 passed, 2 failed
3 tests total, 1 passed, 2 failed```

**Comment by klevenstein** [comment]
Note to self: amend order of labs in the module:
- Intro to pyATS
- Intro to Genie
- Parsers with Genie
- PTS with Genie
- Triggers and Verifications

**Comment by klevenstein** [comment]
Opened #219 to follow up; generally resolved in https://github.com/CiscoDevNet/pyats-labs/releases/tag/1.2
