### ISSUE TITLE
ACI/Kubernetes Sandbox: User cannot connect via SSH to run Ansible playbook in ACI/K8s LL

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#128]
ACI/K8S
https://developer.cisco.com/learning/lab/acik8s-appoptions/step/1 –
Cannot connect via SSH to run Ansible playbook.

**Comment by hpreston** [comment]
@annegentle  I just went through the full lab track and was able to complete everything and get apps deployed.  Can you be more specific about what step resulted in the error above?

**Comment by annegentle** [comment]
@hpreston Thanks for circling back, I re-ran the LL and Ansible works as advertised in the Lab. Since this was first reported in July (I logged the Issue much later), I guess the Sandbox was changed in the meantime. Closing Issue.
