### ISSUE TITLE
Vagrant for Network Engineers Learning Labs do not work due to needing outside access

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#130]
https://developer.cisco.com/learning/modules/vagrant_up/vagrant_101/step/1 

User cannot run the vagrant up command from the DevBox, due to “Couldn’t resolve host ‘vagrantcloud.com’.”

**Comment by annegentle** [comment]
This access should now be available. Update Learning Lab so that the user does not have to do the step that needs external access. (IP address did not change.)

**Comment by annegentle** [comment]
This is also related to Issue #120.

**Comment by vvaliapa** [comment]
I have tested this Lab using the “DevBox” sandbox under DEVNET and added a note for “Vagrant Up” and “Vagrant reload” command in the Learning Lab and published in the testing environment.  Smita wants to test the Lab using the “Devbox Github Access” sandbox under “RA_External_Development”. Karin is working on it.

**Comment by klevenstein** [comment]
Tested; `vagrant up` works, all seems well. Closing.
