### ISSUE TITLE
Multi IOS Sandbox: Introduction to PyATS - DockerHub

### ISSUE THREAD

**Issue by klevenstein** [CiscoDevNet/learning-labs-issues#132]
Multi IOS - Introduction to PyATS
https://developer.cisco.com/learning/lab/intro-to-pyats/step/5
Needs access to DockerHub.

**Comment by annegentle** [comment]
This step 5 should work with the latest image - retest and rewrite instructions if needed.

**Comment by klevenstein** [comment]
Sandbox scheduled for Tuesday 10/15; will test changes then and make updates as needed.
