### ISSUE TITLE
dnav3-code credentials

### ISSUE THREAD

**Issue by klevenstein** [CiscoDevNet/learning-labs-issues#134]
The following lab files may need to have the credentials updated:

dnav3-code/env_lab.py

dnav3-code/intro-dnac/template-prg/env_lab.py
dnav3-code/intro-dnac/cmd-run/env_lab.py
dnav3-code/intro-dnac/path-trace/env_lab.py
dnav3-code/intro-dnac/postman/dnav3-dnac-nbapi-hello-network-env.json
dnav3-code/intro-dnac/template-prg/env_lab.py
dnav3-code/intro-dnac/cmd-run/env_lab.py
dnav3-code/intro-dnac/path-trace/env_lab.py

dnav3-code/postman/dnav3-dnac-nbapi-hello-network-env.json
dnav3-code/postman/DevNet Express DNA CSR1.postman_environment.json
dnav3-code/postman/DevNet Express DNA CSR2.postman_environment.json
dnav3-code/postman/nfvis-api.postman_collection.json

dnav3-code/intro-mdp/postman/DevNet Sandbox RESTCONF Always On.postman_environment.json
dnav3-code/intro-mdp/postman/DevNet Express DNA CSR1.postman_environment.json
dnav3-code/intro-mdp/postman/DevNet Express DNA CSR2.postman_environment.json

dnav3-code/intro-ansible/group_vars/sandbox.yml
dnav3-code/intro-ansible/group_vars/express.yml

dnav3-code/intro-nfvis/Postman/nfvis-api.postman_collection.json

**Comment by annegentle** [comment]
Both credentials will work currently, but the `root` user should not be used going forward. This means that all these code examples need to be changed and tested.

**Comment by klevenstein** [comment]
Track has been updated overall; closing,
