### ISSUE TITLE
ACI/Kubernetes: ACI/Kubernetes LL does not have access to a file needed for Kubernetes

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#136]
Reported by user, “unable to get URL   "https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt":”  

I rebooked the same lab again and it seems that version 1.15 of Kubernetes has broken it:
 
sudo kubeadm init \
   --token ab01bf.1h58iu90bdfr1234 \
   --pod-network-cidr=10.209.0.1/16 \
   --service-cidr=192.168.209.1/24 \
   --apiserver-advertise-address=172.20.9.11
 
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
unable to get URL "https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt": Get https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt: x509: certificate signed by unknown authority
 
whereas when I changed the version to 1.14.3 – latest that worked for me a couple weeks ago, it seemed to work:
 
[developer@sbx09kube01 ~]$ sudo kubeadm init \
>    --token ab01bf.1h58iu90bdfr1234 \
>    --pod-network-cidr=10.209.0.1/16 \
>    --service-cidr=192.168.209.1/24 \
>    --kubernetes-version v1.14.3 \
>    --apiserver-advertise-address=172.20.9.11
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.14.3
 
This is step 8 of said lab: https://developer.cisco.com/learning/tracks/acik8s/acik8s-setup/acik8s-install/step/8

**Comment by hpreston** [comment]
I just tested the lab and it seems to be working for me with the commands as written in the guide.  

The Step 8 Step

```
[developer@sbx29kube01 ~]$ sudo kubeadm init \
>    --token ab01bf.1h58iu90bdfr1234 \
>    --pod-network-cidr=10.229.0.1/16 \
>    --service-cidr=192.168.229.1/24 \
>    --apiserver-advertise-address=172.20.29.11
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.7.16
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks
[preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 17.12.1-ce. Max validated version: 1.12
[kubeadm] WARNING: starting in 1.8, tokens expire after 24 hours by default (if you require a non-expiring token use --token-ttl 0)
[certificates] Generated CA certificate and key.
[certificates] Generated API server certificate and key.
[certificates] API Server serving cert is signed for DNS names [sbx29kube01.localdomain kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [192.168.229.1 172.20.29.11]
[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[apiclient] Created API client, waiting for the control plane to become ready
[apiclient] All control plane components are healthy after 54.501128 seconds
[token] Using token: ab01bf.1h58iu90bdfr1234
[apiconfig] Created RBAC rules
[addons] Applied essential addon: kube-proxy
[addons] Applied essential addon: kube-dns

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run (as a regular user):

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  http://kubernetes.io/docs/admin/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token ab01bf.1h58iu90bdfr1234 172.20.29.11:6443
```

And the final step of that lab shows all 3 nodes up and working on Kubernetes version 1.7.15

```
[developer@sbx29devbox kube_setup]$ kubectl get nodes
NAME                      STATUS     AGE       VERSION
sbx29kube01.localdomain   NotReady   6m        v1.7.15
sbx29kube02.localdomain   NotReady   4m        v1.7.15
sbx29kube03.localdomain   NotReady   4m        v1.7.15
``` 

Maybe it was a point in time problem with the certificate from Google when @annegentle  did the test?

**Comment by annegentle** [comment]
Thanks Hank for investigating - my testing shows the same. This was reported by a user in July, and it looks like the Issue has been resolved since. Closing.
