### ISSUE TITLE
DevBox Sandbox: When using RDP to download Nexus 9000v Switch release, browser says it cannot connect

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#137]
Found in https://developer.cisco.com/learning/lab/vagrant_box_creation/step/2.

On this Learning Lab, the user is instructed to:
---
Navigate to the downloads page for the Nexus 9000v Switch on Cisco.com.

>Note: If you are completing this lab using the DevNet DevBox Sandbox, you'll need to RDP in and download using a web browser on the workstation. There is no way to download the image via the CLI.

---

However, the browser does not ever connect. Tried both "software.cisco.com" and typing in `https://software.cisco.com/download/home/286312239/type/282088129/release/7.0(3)I7(3)`.

<img width="1412" alt="Screen Shot 2019-09-13 at 11 04 05 AM" src="https://user-images.githubusercontent.com/501981/64877087-4367a000-d616-11e9-9d3a-5b89e266881f.png">

**Comment by iceworld** [comment]
devbox i.e. 10.10.20.20 has no outbound connection allowed. Please let us know if a pre-download applicable for this learning lab

**Comment by annegentle** [comment]
@iceworld I think a pre-downloaded copy of the software would be fine for this Learning Lab. Thanks!

**Comment by annegentle** [comment]
Bob will make a new version available and moving to production so we can re-test on a new version of the DevBox. 

The page at https://developer.cisco.com/learning/lab/vagrant_box_creation/step/4 may need to be revised since the software will already be available on-box.

**Comment by annegentle** [comment]
This note on step/4 needs to change: 'Note: If you are completing this lab using the DevNet DevBox Sandbox, you'll need to RDP in and download using a web browser on the workstation. There is no way to download the image via the CLI.'

Basically revise so that the person knows the image is already available on the DevBox.

**Comment by annegentle** [comment]
This note is the one that needs to change: 

"Note: If you are completing this lab using the DevNet DevBox Sandbox, you'll need to RDP in and download using a web browser on the workstation. There is no way to download the image via the CLI."

Revise to: 

"Note: If you are completing this lab using the DevNet DevBox Sandbox, the image is already available to you."

**Comment by klevenstein** [comment]
Published, closing
