### ISSUE TITLE
IOS-XR - Labs in Yang Models and "golang" files in Telemetry and Service Layer Labs are marked as "active": false"

### ISSUE THREAD

**Issue by dethanga** [CiscoDevNet/learning-labs-issues#138]
Hi, 
The complete yang models (5 Labs) and "golang" Labs of telemetry and service layer (2 Labs); total 7 Labs are marked as "**active": false**", hence I have not taken for content review and testing.

**Comment by annegentle** [comment]
I'll close this one since they are meant to be active false and can remain that way in the repo.
