### ISSUE TITLE
IOS XR Programmability: reset_setup.sh output not as expected

### ISSUE THREAD

**Issue by smupad** [CiscoDevNet/learning-labs-issues#140]
**Learning lab**:  https://developer.cisco.com/learning/lab/01-iosxr-01-cli-automation-bash/step/2

**Section**: Introduction: Understanding ZTP and the ZTP bash helper library

In this section, after executing this command: “./reset_setup.sh” 
The command output still shows the old IP address: 10.10.20.170 (instead of the updated IP Address 10.10.20.70). Please refer attached screenshot named “Introduction-router configurations in Devbox”.

<img width="888" alt="Introduction-router configurations in Devbox" src="https://user-images.githubusercontent.com/31358193/65185022-53bfb680-da2c-11e9-8b0f-466e9730bec4.png">

**Comment by smupad** [comment]
Issue possibly could be due to IP address mismatch in the Git repo - https://github.com/CiscoDevNet/iosxr-programmability-devnet-labs-code . IP address needs to be 10.10.20.70 (where it now appears as 10.10.20.170). See occurrences in search - https://github.com/CiscoDevNet/iosxr-programmability-devnet-labs-code/search?q=.170&unscoped_q=.170

**Comment by dethanga** [comment]
@klevenstein 

I updated the new IP address to the respective repo files and raised PR: https://github.com/CiscoDevNet/iosxr-programmability-devnet-labs-code/pull/1 
Kindly verify and approve.

**Comment by dethanga** [comment]
@smupad and @klevenstein, and cc @annegentle 

Updated IP Address to 10.10.20.70 - in all respective files and merged to Master.
