### ISSUE TITLE
Resources not showing up: DevNet Alexa Data Center Skill

### ISSUE THREAD

**Issue by smupad** [CiscoDevNet/learning-labs-issues#142]
**Learning lab**: https://developer.cisco.com/learning/lab/devnet-alexa-lab/step/1 

**Section**: 
Under " A bit about the Learning Lab system itself" it says -
 _When you started this lab you should have noticed a pop-up titled additional resources, like the image below._ 

Issue: Did not get any pop-up. The Learning lab does not show any resources or resources icon.

**Comment by annegentle** [comment]
@movinalot Hey John, do you have ideas on what you'd like to do with this Learning Lab? I think you were using that Lab for a cool demo at a Cisco Live. At this point, probably need to redirect it since people need an Alexa to run it at home. Any thoughts?

**Comment by movinalot** [comment]
@annegentle Hi Anne, this lab was only supposed to be offered at an event. The required resources are not currently supplied or supported.  Also the interfaces' for various aws resources has probably changed.

Hank is bringing online an always-on UCS Manager and you no longer required an Echo to run the lab, the online aws developer tools for the Echo are all that is needed. It's probably possible to rewrite the lab to use those resources.
 
Probably archive the lab until I have an opportunity to update or I could update the lab to indicate that it is a BYOD (bring your own devices)

What do you think about that?

**Comment by klevenstein** [comment]
@annegentle @movinalot For what it's worth, I'm in favor of deactivating for now. We can always resurrect it later.

**Comment by annegentle** [comment]
Agreed, let's redirect to something else for now - such as one of the Data Center/ ACI Learning Labs. Definitely can revisit later. Thanks!

**Comment by johnamcdonough** [comment]
I Agree.

**Comment by klevenstein** [comment]
Maybe this one? https://developer.cisco.com/learning/lab/ucsm-powertool-101/step/1

**Comment by annegentle** [comment]
@dethanga go ahead and add a redirectTo: in the JSON file for this Lab, devnet-alexa-lab, to redirect to ucsm-powertool-101. The redirectTo is documented in this list: https://github.com/CiscoDevNet/devnet-writing-guidelines/wiki/Learning-Labs-JSON-file-parameters

**Comment by dethanga** [comment]
@annegentle 
The updates to the JSON files are completed. The changes are pushed to staging and working fine. 
The fix is: this link https://testing-developer.cisco.com/learning/lab/devnet-alexa-lab/step/1 > will be redirected to https://developer.cisco.com/learning/lab/ucsm-powertool-101/step/1

Should I proceed to Production? Kindly confirm.

**Comment by movinalot** [comment]
I don't think this makes sense. I know I earlier said I agree, but looking at it now I think it would be frustrating to a user to find a lab that they think is one thing and they are redirected to another.

Actually this lab has a good amount of activity.  Let me update it to remove the resource provisioning and indicate how to use the aws built-in tools for alexa skill development.

**Comment by klevenstein** [comment]
Lab is deactivated; closing.
