### ISSUE TITLE
Joy-Workshop: Learning lab is missing link to DevNet Sandbox

### ISSUE THREAD

**Issue by smupad** [CiscoDevNet/learning-labs-issues#147]
**Learning lab**: https://developer.cisco.com/learning/lab/joy-workshop/step/1

**Issue**: This learning lab recommends to use the Joy Sandbox, but does not include a direct link to it. Under the Prerequisites section, please provide a deep link to the **Project Joy** sandbox -https://devnetsandbox.cisco.com/RM/Diagram/Index/f3a7e977-28e4-49e0-8e11-d205edc6959c?diagramType=Topology

**Comment by klevenstein** [comment]
Added a link; the PR can be reviewed/approved here: https://github.com/CiscoDevNet/Joy/pull/5

**Comment by smupad** [comment]
PR looks good. Can be pushed to production.

**Comment by klevenstein** [comment]
Fix merged, published, and released. Closing.
