### ISSUE TITLE
Request for access to https://sandboxdnac.cisco.com/

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#148]
Hi, 
I tried logging into https://sandboxdnac.cisco.com/ and neither my email nor my username works. Can someone please, check my credentials. My email is ktuffent@cisco.com and my user is ktuffent.

Thanks,
Kyle

**Comment by annegentle** [comment]
Hi Kyle, those credentials are common to everyone using that Always-On Sandbox and should be included in the LL itself. Let me know which one this is in and we can add more clear instructions.

**Comment by Reth11** [comment]
I tried to use my personal credentials instead of the learning lab because I guess I was on autopilot logging in. Closing the issue as I was able to log in with the credentials in the lab.
