### ISSUE TITLE
Request Access to Box File.

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#149]
Hi,
I am trying to access a box file at https://cisco.app.box.com/file/519470043160. Could someone please check I have permission.

Thank you,
Kyle

**Comment by annegentle** [comment]
Hey Kyle (@Reth11) , can you give me the LL that this link is found within?

**Comment by Reth11** [comment]
We followed up in chat for https://cisco.app.box.com/file/519470043160. I will contact the owner thanks.
