### ISSUE TITLE
DNAC REST API Layout Considerations

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#150]
### Cisco DNA Center Platform - Authentication
https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1

The formatting of steps seems incorrect. The first and second numbered items are pieces of information needed for step 3 and not really steps. I find the format confusing and the format exists in other places in the lab. Perhaps we can provide the information in step 1 and step 2 inside of step 3.

<img width="822" alt="010" src="https://user-images.githubusercontent.com/50714/65982953-130b6880-e442-11e9-8438-197b52032337.PNG">

**Comment by Reth11** [comment]
We see the same symptom at https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1

**Comment by JoelRiglerIG** [comment]
(1) Primary objection was that numbered sequence 1,2,3, seems to imply steps 1,2,3 when 1, and 2, are really part of the activity that is explained in paragraph 3. This can be fixed with minor rewrite. Other: are (a) minor typos:  'python' rather than 'Python' and 'dtails' rather than 'details'.    See also #186 and #151. 

See also #151, which asks for explanation of saving the authentication token; and #186 (which calls for more explanation of Postman overall).

**Comment by JoelRiglerIG** [comment]
Issues #150, 151, 152, 153, 154, 155, and 186 all relate to a single Learning Lab:  “Cisco DNA Center Platform - Authentication”.   All of these issues were reported by Kyle (Git Id: “Reth11”).  #186 was created by me, by splitting one of Kyle’s reported issues into two separate issue for tracking/resolution purposes, as it appeared to be listing 2 separate ideas.

Notes and ideas:

1) The intent of this exercise is to teach users about using User Credentials to Authenticate to the Intent API.  I think the intro section needs:
1a)  general explanation of the process of authentication;
1b) a little bit about RBAC (roles and rights), (who/what is being authenticated)

2) An explanation of the encoding of the username and password..
2a) the content of the request (“username:password”) formatted and encoded as Basic 64
(Perhaps some very limited background on Basic 64) (see: RFC 2617).  Here is a direct copy from the Wikipedia article on ‘Basic access Authentication”:
“In the context of an HTTP transaction, basic access authentication is a method for an HTTP user agent (e.g. a web browser) to provide a user name and password when making a request. In basic HTTP authentication, a request contains a header field in the form of Authorization: Basic <credentials>, where credentials is the base64 encoding of id and password joined by a single colon :.
It is specified in RFC 7617 from 2015” 
2b) how a user can accomplish this basic 64 encoding.  We could direct users to this website:  (https://www.base64encode.org/) to encode “admin:Cisco123!”.  Its not enough to just show the already encoded value as is currently done.  Users might be using their own DNAC for these exercises. 

3) The resources required needs to be more detailed.  This section seems to be missing as a prerequisite instructions for obtaining the dnav3 repository.  See the top link “How to Setup Your Own Computer” at the top of  https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-cmd-run/step/1.   (That link is NOT in the actual markdown files - I don’t know how it is generated, nor where the content it provides is.). This section includes instruction on getting the ‘dnav3-code’ repository.  This repository contains related sample Python code along with sample Postman code.  The Postman code for this is current not referenced nor described.  However it is the Postman code that can be used as reference content for this. The reference Postman ‘collection’ is in ‘dnav3-code/postman/dnav3-dnac-nbapi-hello-network.json’, and the matching environment is in: “‘dnav3-code/postman/dnav3-dnac-nbapi-hello-network-env.json.  .  (I don’t see a write up of this anywhere and so I’ll do a separate write up and share it. 

4) The use of the Token needs to be explained.  The token is subsequently used in all subsequent API requests in the header. The header for all subsequent calls must have a header parameter (or ‘key’ in Postman) with the name ‘x-auth-token’, set to the value of the returned token.  In the Postman Authentication call, in this collection,  the response to the Auth call is parsed for the token and the global variable {{token}} is set with the the value of the response ‘token’.  This global variable is then used for subsequent call. The documentation for the 1.2.6 API Authentication actually states it pretty well.  It says: 
POST “/dna/system/api/v1/auth/token
Authentication API
API to obtain an access token. The token obtained using this API is required to be set as value to the X-Auth-Token HTTP Header for all API calls to Cisco DNA Center.”
We should quote that and/or redirect users to that documentation section. (https://developer.cisco.com/docs/dna-center/api/1-2-6/, )

5) Page two of this exercise, does not currently reference code from dnav3, but instead seems to be instructing users to create a new Python source file and then run it.  If that is the case, lets make sure it works.  Or we could add a source module to the dnav3-code repository specifically for this section.  Right now there is no existing match in the dnav3-code repository,.  There is a similar but not identical ‘get_auth_token()’ function, in ’dance-nbapi-hello-world.py’.

**Comment by srshalini** [comment]
> ### Cisco DNA Center Platform - Authentication
> https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1
> 
> The formatting of steps seems incorrect. The first and second numbered items are pieces of information needed for step 3 and not really steps. I find the format confusing and the format exists in other places in the lab. Perhaps we can provide the information in step 1 and step 2 inside of step 3.
> 
> <img alt="010" width="822" src="https://user-images.githubusercontent.com/50714/65982953-130b6880-e442-11e9-8438-197b52032337.PNG">



> ### Cisco DNA Center Platform - Authentication
> https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1
> 
> The formatting of steps seems incorrect. The first and second numbered items are pieces of information needed for step 3 and not really steps. I find the format confusing and the format exists in other places in the lab. Perhaps we can provide the information in step 1 and step 2 inside of step 3.
> 
> <img alt="010" width="822" src="https://user-images.githubusercontent.com/50714/65982953-130b6880-e442-11e9-8438-197b52032337.PNG">



> ### Cisco DNA Center Platform - Authentication
> https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1
> 
> The formatting of steps seems incorrect. The first and second numbered items are pieces of information needed for step 3 and not really steps. I find the format confusing and the format exists in other places in the lab. Perhaps we can provide the information in step 1 and step 2 inside of step 3.
> 
> <img alt="010" width="822" src="https://user-images.githubusercontent.com/50714/65982953-130b6880-e442-11e9-8438-197b52032337.PNG">

The steps have been formatted.
