### ISSUE TITLE
DNAC Request Information to Become an Additional Step

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#151]
### Cisco DNA Center Platform - Authentication
https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1
Recording the token could be more clear if marked as a step. We could mark this as step 4.

<img width="901" alt="011" src="https://user-images.githubusercontent.com/50714/65983136-801efe00-e442-11e9-9e55-d690ba1eebaf.PNG">

**Comment by srshalini** [comment]
> ### Cisco DNA Center Platform - Authentication
> https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1 Recording the token could be more clear if marked as a step. We could mark this as step 4.
> 
> <img alt="011" width="901" src="https://user-images.githubusercontent.com/50714/65983136-801efe00-e442-11e9-9e55-d690ba1eebaf.PNG">

Marked as a separate step.
