### ISSUE TITLE
DNAC: Missing Requirement for PIP

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#152]
### Cisco DNA Center Platform - Authentication
https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/2

Need a requirement for PIP being installed as PIP is not installed by default.

https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1
<img width="692" alt="012" src="https://user-images.githubusercontent.com/50714/65987487-85347b00-e44b-11e9-82c8-f755d1cbe12b.PNG">

**Comment by srshalini** [comment]
> ### Cisco DNA Center Platform - Authentication
> https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/2
> 
> Need a requirement for PIP being installed as PIP is not installed by default.
> 
> https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1 <img alt="012" width="692" src="https://user-images.githubusercontent.com/50714/65987487-85347b00-e44b-11e9-82c8-f755d1cbe12b.PNG">

Have included the PIP step.
