### ISSUE TITLE
DNAC Separate File Segments

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#153]
### Cisco DNA Center Platform - Authentication
https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/2

In the lab, the file is broken up into segments. It is unclear the name of the file or that we should be generating the file with all the segments. May we please, have the file all together in one section? It would also be nice to have the command to run the python as this adds clarity to the objective.

**Comment by Reth11** [comment]
Where should the python code run from? Inside a container, outside a container, from a special directory? Do we need a special user to run the python code?

**Comment by Reth11** [comment]
### Cisco DNA Center Platform - Network Devices
https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/2

Where are we running the python code from?

**Comment by JoelRiglerIG** [comment]
In triage, this is now for File merge rewrite only.   I moved created separate issue (#187  for questions regarding context for client.

**Comment by srshalini** [comment]
> ### Cisco DNA Center Platform - Network Devices
> https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/2
> 
> Where are we running the python code from?

This has been mentioned.
