### ISSUE TITLE
DNAC Step To Record Token

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#154]
### Cisco DNA Center Platform - Authentication
https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/2

There is not a step to record the token. May we please, add a step to record the token? The token is referenced later on in the lab.

**Comment by JoelRiglerIG** [comment]
Appears to be duplicate to #151 .

**Comment by JoelRiglerIG** [comment]
Functional duplicate to #151
