### ISSUE TITLE
DNAC Error Message When Executing Python Script

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#155]
### Cisco DNA Center Platform - Authentication
https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/2

The following error message is generated when running the python script from a container.

```
		root@83a57496a4bb:/home/coder/DNA# python sample.py
		Traceback (most recent call last):
		  File "sample.py", line 3, in <module>
		    from dnac_config import DNAC, DNAC_PORT, DNAC_USER, DNAC_PASSWORD
		  File "/home/coder/DNA/dnac_config.py", line 3, in <module>
		    from dnac_config import DNAC, DNAC_PORT, DNAC_USER, DNAC_PASSWORD
		ImportError: cannot import name DNAC
```

Do we need to import the DNAC library? If we do need to import the library, how do we install the library?

**Comment by JoelRiglerIG** [comment]
Mistakenly closed this issue.  Re-opened and reassigned to myself.
