### ISSUE TITLE
DNAC Request for Extra Content

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#158]
### Cisco DNA Center Platform - Network Devices
https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1

May we please, have Instructions to click on the "PROVISION" tab in the lab?

<img width="657" alt="014" src="https://user-images.githubusercontent.com/50714/65996486-1bbd6800-e45d-11e9-8275-5d5731196335.PNG">

In my experience trusting a baseline user experience above anything other than none results in tickets and questions. I think it would be helpful to have verbiage about to get to the provisioning tab. As the lab is currently setup, the user does not start in the beginning and might be considered in the middle of the application.

**Comment by srshalini** [comment]
> ### Cisco DNA Center Platform - Network Devices
> https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1
> 
> May we please, have Instructions to click on the "PROVISION" tab in the lab?
> 
> <img alt="014" width="657" src="https://user-images.githubusercontent.com/50714/65996486-1bbd6800-e45d-11e9-8275-5d5731196335.PNG">
> 
> In my experience trusting a baseline user experience above anything other than none results in tickets and questions. I think it would be helpful to have verbiage about to get to the provisioning tab. As the lab is currently setup, the user does not start in the beginning and might be considered in the middle of the application.

The steps have been included with the updated screenshot.
