### ISSUE TITLE
DNAC Request for Updated Image

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#159]
### Cisco DNA Center Platform - Network Devices
https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1

This is a minor issue. This is a hosted environment for the lab. My lab only has two network devices whereas the image has four.

Image below is from the lab document (Expected)
<img width="873" alt="015" src="https://user-images.githubusercontent.com/50714/65996901-f3823900-e45d-11e9-9197-499365a5bf04.PNG">
 
The image below is from my lab. (Actual)
<img width="913" alt="016" src="https://user-images.githubusercontent.com/50714/65997181-80c58d80-e45e-11e9-8880-1ed6cf07d6fc.PNG">

**Comment by JoelRiglerIG** [comment]
This request is to match the explanation to a specific Sandbox configuration at a specific time.  Probably 'wont-do' as written, but could  provide information making it more general

**Comment by srshalini** [comment]
> ### Cisco DNA Center Platform - Network Devices
> https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1
> 
> This is a minor issue. This is a hosted environment for the lab. My lab only has two network devices whereas the image has four.
> 
> Image below is from the lab document (Expected) <img alt="015" width="873" src="https://user-images.githubusercontent.com/50714/65996901-f3823900-e45d-11e9-9197-499365a5bf04.PNG">
> 
> The image below is from my lab. (Actual) <img alt="016" width="913" src="https://user-images.githubusercontent.com/50714/65997181-80c58d80-e45e-11e9-8880-1ed6cf07d6fc.PNG">

Have included the updated image.
