### ISSUE TITLE
DNAC Request for Transition

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#160]
# Cisco DNA Center Platform - Network Devices
https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1

The formatting on the lab is very odd. The images do not have text that reference them. The flow of the lab is looking at images and then all of sudden have to key pieces of information that doesn't explain where they came from. Follow this example we are now working in Postman without any transition.

<img width="638" alt="017" src="https://user-images.githubusercontent.com/50714/65997499-1cef9480-e45f-11e9-82d0-0e9d516469e0.PNG">

**Comment by JoelRiglerIG** [comment]
I interpret this 'issue' as basically asking for this lab to be written better with more logical flow. There does not seem to be any specific issue identified.

**Comment by srshalini** [comment]
> # Cisco DNA Center Platform - Network Devices
> https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1
> 
> The formatting on the lab is very odd. The images do not have text that reference them. The flow of the lab is looking at images and then all of sudden have to key pieces of information that doesn't explain where they came from. Follow this example we are now working in Postman without any transition.
> 
> <img alt="017" width="638" src="https://user-images.githubusercontent.com/50714/65997499-1cef9480-e45f-11e9-82d0-0e9d516469e0.PNG">

have included a proper image.
