### ISSUE TITLE
DNAC - DNAC - Missing step to record MAC and IP Address

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#162]
### Cisco DNA Center Platform - Network Devices
https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1

We are missing a step to record the MAC and IP address. There is a lot of information to shift through. If the customer had hundreds of devices is there a way to just get results for a name, mac, and IP?

**Comment by JoelRiglerIG** [comment]
Split question part of this into a separate issue #189

**Comment by JoelRiglerIG** [comment]
Also changed title to just be for "Missing Step..."

**Comment by srshalini** [comment]
> ### Cisco DNA Center Platform - Network Devices
> https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1
> 
> We are missing a step to record the MAC and IP address. There is a lot of information to shift through. If the customer had hundreds of devices is there a way to just get results for a name, mac, and IP?

Have included the appropriate steps.
