### ISSUE TITLE
Minor DNAC Recommendation For Block Quoting

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#163]
### Cisco DNA Center Platform - Network Devices

https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1

Recommend not to use block quotes for normal instructions.

<img width="838" alt="018" src="https://user-images.githubusercontent.com/50714/66000600-64791f00-e465-11e9-8816-df1b396b774a.PNG">

**Comment by JoelRiglerIG** [comment]
@Reth11:  Can you please explain objection further?

**Comment by Reth11** [comment]
@JoelRiglerIG 
Normally the gray bar seen in the picture is used for block quotes. In the instructions, it is used as an item or next step, which is not quoting anything. I recommend using an astrick or a number.

**Comment by JoelRiglerIG** [comment]
Removing "Clarify Issue" tag.  While I don't see a 'gray bar' in either the screenshot, nor when looking at the lab instruction,  I do see that the formatting is different with large font rather than looking like text in a step.  Perhaps the gray is browser specific.

**Comment by srshalini** [comment]
> ### Cisco DNA Center Platform - Network Devices
> https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1
> 
> Recommend not to use block quotes for normal instructions.
> 
> <img alt="018" width="838" src="https://user-images.githubusercontent.com/50714/66000600-64791f00-e465-11e9-8816-df1b396b774a.PNG">

This issue has been resolved.
