### ISSUE TITLE
DNAC Mismatch on Reference

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#164]
# Cisco DNA Center Platform - Network Devices
https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1

Missing step to record deviceId, which is referenced as "id" in the output from Postman and not deviceId. Later on, in the labs the deviceId is requested.

<img width="421" alt="019" src="https://user-images.githubusercontent.com/50714/66001132-832be580-e466-11e9-8721-fa620171b0ff.PNG">

https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/3

<img width="746" alt="020" src="https://user-images.githubusercontent.com/50714/66001563-53311200-e467-11e9-9ddf-f61777dfacba.PNG">

**Comment by JoelRiglerIG** [comment]
@Reth11 - Can you clarify this issue?  Is this an objection to the name of the parameter on this page: "https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/3" (not step 1).

**Comment by Reth11** [comment]
@JoelRiglerIG 
In step 1 the user is asked to run an API call. In step 3 they are asked to use information from step 1, except that they may have closed the window with the information or some other action as the lab did not request the user to record the information. In step 3 the variable referencing the information is called "deviceId" and the information is returned with a label "id", which is different from the request.

**Comment by srshalini** [comment]
> # Cisco DNA Center Platform - Network Devices
> https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1
> 
> Missing step to record deviceId, which is referenced as "id" in the output from Postman and not deviceId. Later on, in the labs the deviceId is requested.
> 
> <img alt="019" width="421" src="https://user-images.githubusercontent.com/50714/66001132-832be580-e466-11e9-8721-fa620171b0ff.PNG">
> 
> https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/3
> 
> <img alt="020" width="746" src="https://user-images.githubusercontent.com/50714/66001563-53311200-e467-11e9-9ddf-f61777dfacba.PNG">

This is resolved.
