### ISSUE TITLE
DNAC Line Numbers for Code

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#165]
### Cisco DNA Center Platform - Network Devices
https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/2

Recommend line numbers for the code and then referencing those line numbers when explaining functionality.

Currently in the lab we see the following image.
<img width="517" alt="021" src="https://user-images.githubusercontent.com/50714/66001943-2f220080-e468-11e9-9ff3-cdbf48abdcf1.PNG">

Requesting line numbers as in the below example.
<img width="462" alt="022" src="https://user-images.githubusercontent.com/50714/66001964-38ab6880-e468-11e9-98ec-0fef5993ccd5.PNG">

**Comment by srshalini** [comment]
The line numbers have been included.
The code has been broken up into pieces by functions with explanations and is now easier to reference.
Thank You.
