### ISSUE TITLE
DNAC Request Corresponding Command for Output

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#166]
### Cisco DNA Center Platform - Network Devices
https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/2

The output is shown, but we do not see the input for the command's output. Please, list the command.

<img width="601" alt="023" src="https://user-images.githubusercontent.com/50714/66002116-92139780-e468-11e9-92cd-1a92eb70e208.PNG">

**Comment by JoelRiglerIG** [comment]
@Reth11:  can you please review/expand on this issue.  The output result for the Python script seems to be there - and is shown in your provided screenshot, under the sentence: "Successfully executing the code will output:".  Can you please explain what else you are looking for?

**Comment by Reth11** [comment]
@JoelRiglerIG  
What command was ran to get the output?

**Comment by JoelRiglerIG** [comment]
@Reth11 ,   In this case the 'command' used to get the instruction was to run the Python script.  I could add that line, and it might be helpful - but I'm guessing that the original author expected Lab participant to have at this point in the sequence to understand how to run a Python script.  The Prerequisite for this sequence ('step/1') has "Setup Python", but does not direct the users to any basic 'Hello World' kind of tutorial at each stage. That might be useful. 

What I see missing is instructions as to where the user gets the support module "dnac_config".  That seems to be a basic that is missing from a number of these lab sequences. 

I'm going to look for a way provide a general "setup for these labs" instructions - that include a general list of "you should know before starting" and "obtaining resources" kind of instructions.  I'd welcome any suggestions for content or comments on that approach.

**Comment by JoelRiglerIG** [comment]
@Reth11 If I understood your "What command was ran to get the output?" response correctly, and my comment above meets your needs,  let me know and I'll remove the "Clarify Issue" tag. If not, can you - please review and clarify further.

**Comment by Reth11** [comment]
In my experience working support and following instructions, it is good to have everything spelled out without exception. I am sure some of our customers will have no problem with the omission and then there will be customers that are new. In my opinion, having the instruction and output makes the lab look more polished.
