### ISSUE TITLE
DNAC Request for Answer to Question

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#167]
### End to End Visibility and Assurance with Path Trace and Cisco DNA Center Platform
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-path-trace/step/2

Under the section, "Which API Should I Use?" the answer doesn't indicate which API.

<img width="924" alt="024" src="https://user-images.githubusercontent.com/50714/66002413-444b5f00-e469-11e9-9e8b-90b82a56efe7.PNG">

**Comment by JoelRiglerIG** [comment]
Doc should be improved to let the user know that the answer this this question is on the following page /step.  There is an answer to 'which API should I use on the next page (/step/3) albeit an incorrect answer. Referring to it as "Inventory" is also incorrect. 
 I created a #190 to address the incorrect answer.

**Comment by vvaliapa** [comment]
APIC-EM is no longer supported. Hence retiring the Lab.
