### ISSUE TITLE
DNAC Request to Add Credentials to Instructions

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#168]
### End to End Visibility and Assurance with Path Trace and Cisco DNA Center Platform
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-path-trace/step/2

Request to add credentials to instructions as they are static.

```
Host: sandboxdnac.cisco.com
me: devnetuser
Password: Cisco123!
```

**Comment by vvaliapa** [comment]
Whenever sandbox changes, credentials also might change. So it will be difficult to update every time. Closing this issue as we won't fix it.
