### ISSUE TITLE
DNAC Bad Character in Code

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#169]
### End to End Visibility and Assurance with Path Trace and Cisco DNA Center Platform
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-path-trace/step/4

Line 9 has a bad character at the end, which is causing an error at run time.

<img width="716" alt="025" src="https://user-images.githubusercontent.com/50714/66002696-e4a18380-e469-11e9-884f-4cae797ad6c1.PNG">

**Comment by vvaliapa** [comment]
Fixed and closing the issue.
