### ISSUE TITLE
DNAC Traceback when Running Code

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#170]
### End to End Visibility and Assurance with Path Trace and Cisco DNA Center Platform
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-path-trace/step/4

The script generated a traceback;

```
		root@83a57496a4bb:/home/coder/DNA# python print_token.py
		Traceback (most recent call last):
		  File "print_token.py", line 14, in <module>
		    apic_login(apicem['host'], apicem['username'], apicem['password'])
		NameError: name 'apicem' is not defined
```

I think I am missing a library. I tried the code with variables substituted which had the same result.

**Comment by JoelRiglerIG** [comment]
Step 4 here just seems to be for an unrelated API (APIC) and not Intent API.  This seems more like a completely wrong step for this section and unrelated to this Learning Lab.  See also #190, which references incorrect APIs.  Seems possible this LL was never stepwise tested (until now - thanks Kyle).

**Comment by vvaliapa** [comment]
APIC-EM is no longer supported. Hence retiring the Lab.
