### ISSUE TITLE
DNAC Whitespace Python Code path_trace.py

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#171]
### End to End Visibility and Assurance with Path Trace and Cisco DNA Center Platform
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-path-trace/step/4

Error when running path_trace.py code. I removed all the whitespace at the beginning and received a new message.

<img width="645" alt="026" src="https://user-images.githubusercontent.com/50714/66003166-f33c6a80-e46a-11e9-860a-9a95dfacae1b.PNG">

From the following message, I think I am missing an import.

```
		root@83a57496a4bb:/home/coder/DNA# python path_trace.py
		  File "path_trace.py", line 2
		    parser = argparse.ArgumentParser()
		    ^
```

**Comment by vvaliapa** [comment]
APIC-EM is no longer supported. Hence retiring the Lab.
