### ISSUE TITLE
DNAC Script Issues and Patch Form Style Requested for Updates to Code

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#172]
### End to End Visibility and Assurance with Path Trace and Cisco DNA Center Platform
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-path-trace/step/5

When making changes to an existing file recommend using the patch format.
Here is a URL for an example, https://www.thegeekstuff.com/2014/12/patch-command-examples
I think this step is recommending to update the path_trace.py. I am not really sure as I could not get the python script to successfully run.

<img width="748" alt="027" src="https://user-images.githubusercontent.com/50714/66003342-71007600-e46b-11e9-8d95-4d177b04d67f.PNG">

**Comment by JoelRiglerIG** [comment]
@Reth11 :  Can you clarify this recommendation.  Why are you suggesting use of a patch approach rather than directly creating and editing the source files?

**Comment by Reth11** [comment]
I have two points in mind for the reasoning behind the patch. 
1) Another form of version control
2) If they ever have to deploy the change to many systems at once then it would be better than manually editing a text file.

If neither of those applies, then please close the issue.

**Comment by vvaliapa** [comment]
This Lab has APIC-EM which is no longer supported. Hence deactivated the Lab.
