### ISSUE TITLE
Meraki module | redirection

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#173]
After sign-in on this page, https://developer.cisco.com/learning/tracks/meraki users redirected on this https://developer.cisco.com/learning/
This is not convenient because еhen users need to search the page https://developer.cisco.com/learning/tracks/meraki again

**Comment by annegentle** [comment]
I will report this bug to the LL platform team - it tends to re-occur every once in a while.

**Comment by annegentle** [comment]
@oborys When I use an Incognito window, I cannot replicate on Mac on Chrome - can you indicate your OS and browser? And if you had already logged into the main DevNet site?

**Comment by oborys** [comment]
@annegentle  I replicate it on Mac on Firefox in Incognito tab. I try to record it but after once I saw this, next sign-in goes without a problem.

**Comment by annegentle** [comment]
Let's close, this does happen occasionally but the LL engineering can't accommodate this fix.
