### ISSUE TITLE
Meraki module | Meraki Always On Sandbox

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#175]
In Meraki Overview tab here
https://devnetsandbox.cisco.com/RM/Diagram/Index/a9487767-deef-4855-b3e3-880e7f39eadc?diagramType=Topology
Add tooltip in "Access Details" chapter, like "After type-in Username, click "Log in to personal account" and enter password" 
Also, input space here "Password:ilovemeraki"

**Comment by annegentle** [comment]
@oborys This content is in this repo: https://github.com/CiscoDevNet/sandbox-instructions and I have added you with Write access so that you can make these changes. It's HTML rather than Markdown, but fairly simple to work on. I can help with reviews in that repo.

**Comment by oborys** [comment]
@annegentle thanks. I've created this PR https://github.com/CiscoDevNet/sandbox-instructions/pull/17 I close this issue
