### ISSUE TITLE
Meraki module | link to MSB Sandbox

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#177]
On this page https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-01-integrations/step/4 in the chapter "Enable Scanning API"
add a link on this page https://devnetsandbox.cisco.com/RM/Diagram/Index/9b70e4ec-f927-4e69-8742-4cfb0f45b145 for this words "Meraki Small Business Sandbox".

**Comment by vvaliapa** [comment]
Fixed the issue. Here is the link:  https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-01-integrations/step/4
