### ISSUE TITLE
Meraki module | MSB Sandbox missing dropdown box "Scanning API"

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#178]
In Meraki Dashboard of Meraki Small Business Sandbox (https://devnetsandbox.cisco.com/RM/Diagram/Index/9b70e4ec-f927-4e69-8742-4cfb0f45b145) missing dropdown box "Scanning API". So users can't enable and test these features.

**Comment by oborys** [comment]
If we navigate Network-wide -> General in different Meraki Sandbox I found that 
"Location and scanning" block is available only in Meraki Enterprise Sandbox.
So it's good to notice about this in LL.

**Comment by denapom11** [comment]
This issue has been addressed with several updates to the labs in December 2019.

**Comment by denapom11** [comment]
LL no longer uses sandbox
