### ISSUE TITLE
Meraki module | API & Bluetooth Scanning settings

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#179]
On this page https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-01-integrations/step/4 mentioned "Enable Scanning API" and "Enable Bluetooth Scanning", but there are no corresponding settings in the Meraki dashboard (Meraki Small Business Sandbox)

**Comment by oborys** [comment]
If we navigate Network-wide -> General in different Meraki Sandbox I found that 
"Location and scanning" block is available only in Meraki Enterprise Sandbox.
So it's good to notice about this in LL.

**Comment by denapom11** [comment]
This issue has been addressed with several updates to the labs in December 2019.

**Comment by denapom11** [comment]
LL no longer uses sandbox
