### ISSUE TITLE
Meraki module | Dockerfile

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#181]
On this page
https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-03-location-scanning-python/step/1
In chapter "Option 3 Prerequisite steps"

We see strings in LL
**5. Open ~/meraki-code/meraki-location-scanning-python/locationscanningreceiver/Dockerfile.
6. Update `CMD python locationscanningreceiver.py -v simulator -s scanninglab` by replacing simulator with the validator copied from the Meraki Dashboard.**

but in Dockerfile I found this string wich have different parameter (`simulator` insted of `scanninglab`)
String in Docerfile
`CMD ["python", "locationscanningreceiver.py", "-v", "simulator", "-s", "simulator"]`

**Comment by klevenstein** [comment]
Fixed, closing.
