### ISSUE TITLE
Meraki module | scanninglab parameter & Location and Scanning

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#182]
On this page https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-03-location-scanning-python/step/3
we see "Login to the DevNet Sandbox and select the lab Meraki Small Business..."
In MSB Sandbox I can't find "Location and Scanning" section and two points bellow cannot be fulfilled
```
2. Under Network, select Network-wide->General.
3. Scroll down to Location and Scanning and verify the API is enabled.
```
Also does not specify where to change the parameter "Secret" and where to take the parameter "scanninglab"
`5. Set the Secret to scanninglab.`

**Comment by oborys** [comment]
If we navigate Network-wide -> General in different Meraki Sandbox I found that 
"Location and scanning" block is available only in Meraki Enterprise Sandbox.
So it's good to notice about this in LL.

**Comment by denapom11** [comment]
This issue has been addressed with several updates to the labs in December 2019.

**Comment by denapom11** [comment]
LL no longer uses sandbox
