### ISSUE TITLE
Meraki module | lab link

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#184]
On this page https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-06-wireless-health/step/1
Text "REST API Fundamentals" should be a link to this lab https://developer.cisco.com/learning/lab/coding-101-rest-basics-ga/step/1

**Comment by vvaliapa** [comment]
Updates are done hence closing this issue.
Here is the link:  https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-06-wireless-health/step/4
