### ISSUE TITLE
Broken links in DNE DCI Learning Labs - to docs.microsoft.com and wikipedia

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#185]
Looks like these may be caused by encoded URLs, or maybe the Markdown itself is incorrect? 

FILE: ./labs/dne-dcip-introduction-to-powershell-introduction-v01/3.md
[✖] https://blogs.technet.microsoft.com/pstips/2014/06/17/powershell-scripting-best-practices/

FILE: ./labs/dne-dcip-introduction-to-powershell-mission-01-v01/4.md
[✖] https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/about_Hash_Tables?view=powershell-5.1
[✖] https://en.wikipedia.org/wiki/Comparison_of_programming_languages_&#40;associative_array&#41;

FILE: ./labs/dne-dcip-introduction-to-powershell-mission-02-v01/3.md
[✖] https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/about_Hash_Tables?view=powershell-5.1
[✖] https://en.wikipedia.org/wiki/Comparison_of_programming_languages_&#40;associative_array&#41;

**Comment by annegentle** [comment]
This link is still reporting as broken:
FILE: ./labs/dne-dcip-introduction-to-powershell-pipelining-and-output-v01/1.md
[✖] https://msdn.microsoft.com/en-us/powershell/scripting/powershell-scripting

**Comment by annegentle** [comment]
I think these are the old DevNet Express LL and this repo can be archived. @klevenstein can you investigate?

**Comment by klevenstein** [comment]
These labs are currently linked on the DCI DNE track, so I went ahead and updated the PowerShell scripting link; will publish.
