### ISSUE TITLE
DNAC: "Getting Started...DNA Center" - With Authentication API - Postman

### ISSUE THREAD

**Issue by JoelRiglerIG** [CiscoDevNet/learning-labs-issues#186]
https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1

This section needs more explanation of use of Postman.  There is a link in the prerequisites to the Postman website for installation, but no explanation at all.  This needs both a general explanation of the tool - and a specific one for how to execute the authentication commands and to save the returned authentication token.

**Comment by srshalini** [comment]
> https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/1
> 
> This section needs more explanation of use of Postman. There is a link in the prerequisites to the Postman website for installation, but no explanation at all. This needs both a general explanation of the tool - and a specific one for how to execute the authentication commands and to save the returned authentication token.

The general explanation of the tool Postman is already mentioned in the Postman site link.
