### ISSUE TITLE
DNAC: Provide information/constraints to user w/regard to client OS

### ISSUE THREAD

**Issue by JoelRiglerIG** [CiscoDevNet/learning-labs-issues#187]
https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/2

(Moved 2nd issue from #153  to here so as to address each issue separately.)
"Where should the python code run from? Inside a container, outside a container, from a special directory? Do we need a special user to run the python code?"

**Comment by srshalini** [comment]
> https://developer.cisco.com/learning/modules/dnac-rest-apis/auth/step/2
> 
> (Moved 2nd issue from #153 to here so as to address each issue separately.) "Where should the python code run from? Inside a container, outside a container, from a special directory? Do we need a special user to run the python code?"

Already mentioned.
