### ISSUE TITLE
DNAC - Question: network devices:  Way to get results for name, MAC, and IP if there are hundreds of devices?

### ISSUE THREAD

**Issue by JoelRiglerIG** [CiscoDevNet/learning-labs-issues#189]
(split from #162 - as 2nd issue):

https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1

If the customer had hundreds of devices is there a way to just get results for a name, mac, and IP?

**Comment by srshalini** [comment]
> (split from #162 - as 2nd issue):
> 
> https://developer.cisco.com/learning/modules/dnac-rest-apis/network_device/step/1
> 
> If the customer had hundreds of devices is there a way to just get results for a name, mac, and IP?

The above has been added under the "Check specific devices" section.
