### ISSUE TITLE
DNAC:  Incorrect API URL and description of API method 'group' name.

### ISSUE THREAD

**Issue by JoelRiglerIG** [CiscoDevNet/learning-labs-issues#190]
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-path-trace/step/3

Group (Inventory), associated Diagram and specific URLs are all incorrect for 1.2.5+

As shown (wrong)  
https://{}/api/system/v1/auth/token 
https://{}/api/v1/network-device 
https://{}/api/v1/interface 
https://{}/api/v1/host 
https://{}/api/v1/flow-analysis 

Correct 1.2.5+ API URLs are:
for Authentication:  "/dna/system/api/v1/auth/token"
and 
/dna/intent/api/v1/network-device
as so on.

Also there is no 'Inventory' subdomain. This should be "Know Your Network" and then "Devices".

**Comment by annegentle** [comment]
https://{}/api/v1/network-device should be : https://{}/dna/intent/api/v1/network-device
and so on:
/dna/intent/api/v1/interface

**Comment by vvaliapa** [comment]
APIC-EM is no longer supported. Hence retiring the Lab.
