### ISSUE TITLE
DNAC Missing Script show_command.py

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#193]
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-cmd-run/step/3

The show_command.py is referenced twice and I am not seeing the script.

<img width="588" alt="31" src="https://user-images.githubusercontent.com/50714/66435263-137ba480-e9ea-11e9-85b1-5809d29d9eaa.PNG">
<img width="419" alt="032" src="https://user-images.githubusercontent.com/50714/66435264-137ba480-e9ea-11e9-9f57-a77ed725cf30.PNG">

**Comment by vvaliapa** [comment]
Fixed the issue
