### ISSUE TITLE
DNAC Rest API Request to Add Instructions on Accessing Template Editor

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#194]
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-template-prg/step/1

We can find the template editor by using Ctrl-F and searching for a template. I recommend adding some instructions to avoid the customer guessing.

<img width="696" alt="033" src="https://user-images.githubusercontent.com/50714/66435579-cc41e380-e9ea-11e9-9b29-30ac742c837b.PNG">

**Comment by JoelRiglerIG** [comment]
Also relates to #197

**Comment by vvaliapa** [comment]
Updated the Lab and published.
