### ISSUE TITLE
DNAC Template Group Sydney-Deployment is Missing

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#196]
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-template-prg/step/1

While following allow with the lab, the template Sydney-Deployment is missing. The Sydney group did not have the "Change Description" template either.

Below is the lab screen shots referencing Sydney-Deployment
<img width="732" alt="039" src="https://user-images.githubusercontent.com/50714/66436322-5c345d00-e9ec-11e9-84dc-eef9607bfb00.PNG">

Below are two screen shots referencing the templates in Sydney
<img width="300" alt="037" src="https://user-images.githubusercontent.com/50714/66436128-f9db5c80-e9eb-11e9-850f-7a9ddf74bdc1.PNG">
<img width="288" alt="038" src="https://user-images.githubusercontent.com/50714/66436129-fa73f300-e9eb-11e9-8107-07eafc036f64.PNG">

**Comment by JoelRiglerIG** [comment]
Sandbox is generally open to the public - which means that templates could be deleted.  We either need to find a way to reset a base structure - or assume not specific resources in the Sandbox DNA Center.

**Comment by annegentle** [comment]
The template editor now contains this Sydney Deployment entry, so we believe it has been reset. Closing.
