### ISSUE TITLE
DNAC Question Where Do We Find Operational Tools

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#197]
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-template-prg/step/1

Where do we find "Operational Tools -> Template Programmer"?
<img width="732" alt="039" src="https://user-images.githubusercontent.com/50714/66437033-50e23100-e9ee-11e9-906b-6836711352ff.PNG">

**Comment by jrigler** [comment]
DNAC Platform bundle is not visible in either of the Always On Sandboxes.  So revising this from 'Doc omission' / 'enhancement' to 'Learning Lab' issue. (Needs to be on.)

**Comment by vvaliapa** [comment]
Updated the required information.
