### ISSUE TITLE
DNAC How Do We Use the API Calls

### ISSUE THREAD

**Issue by Reth11** [CiscoDevNet/learning-labs-issues#199]
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-template-prg/step/3

How do we use the API calls? I referenced the previous calls using Postman, but these seem to be missing the first part of the URL. The example does not contain how the API call was done.

```
POST /v1/template-programmer/template/deploy which applies the template and returns a deploymentId.
GET /v1/template-programmer/template/deploy/status/{deploymentId} - poll until it completes and show the status.
```

<img width="757" alt="041" src="https://user-images.githubusercontent.com/50714/66437735-314c0800-e9f0-11e9-9279-23486855926c.PNG">

**Comment by JoelRiglerIG** [comment]
1) Incorrect, incomplete URLs (omits the 'intent/api/ prefix)
2) Should have minimal reference to how to use Postman - or direction to prerequisites.

**Comment by vvaliapa** [comment]
Updated the correct URL. Directions for how to use Postman are not updated as the Lab is interactive now.
