### ISSUE TITLE
Meraki module | can't use POST in Sandbox

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#201]
Using Meraki Enterprise Sandbox can't sent POST request by Postman.
Get 403 error
Try different variants from creating a network to reboot the device by serial number.

**Comment by oborys** [comment]
On this page, https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-07-webhooks/step/1 note that for "Option #3 (DevNet Sandbox)" only few post method are allowed (for the correct network  with user email address appended to the name) one of it is POST {{baseUrl}}/networks/{{networkId}}/groupPolicies

**Comment by denapom11** [comment]
This issue has been addressed with several updates to the labs in December 2019.  The enterprise sandbox is no longer used.
