### ISSUE TITLE
Meraki module | Webhooks HTTP server, failed

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#202]
Going through this instruction https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-07-webhooks/step/3
can't create Webhooks HTTP server
enter Name, URL, Shared secret and press "Send test webhook" and get failed.
Sandbox - Meraki Enterprise

**Comment by oborys** [comment]
The problem connected with trying to add it for the wrong network.
The suggestion is to add item on this page -https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-07-webhooks/step/3
for this chapter "If you chose Option 2 or 3 at the beginning of the lab, follow these steps"
extend list item 2 by add info
"For choose correct network go to Dashboard and in search for network field start to enter your email, and chose the network with your email address appended to the name"

In item 5 extra symbol at the end of string "*". Or add the notice like 
"* Insert secrete that you wrote in command `python webhookreceiver.py -s <Shared_secret>`"

**Comment by dethanga** [comment]
@denapom11 and cc @annegentle 
Hi Matt - With regard to this issue, the submitter is requesting for LL changes: Adding a note next to procedure number 5 in step 3: https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-07-webhooks/step/3
I am unable to access the URLs http://locahost:5001/go and http://localhost:5005 mentioned under "Launch Webhook Simulator" section in step 3

Also, we have an issue belongs to the same LL referring to step 1; where using Meraki Enterprise Sandbox can't be sent POST request by Postman. Getting a 403 error. https://github.com/CiscoDevNet/learning-labs-issues/issues/201

I need your help with more clarity to understand and fix this issue. Kindly check and advise.

Thanks - Devi

**Comment by denapom11** [comment]
This issue has been addressed with several updates to the labs in December 2019.  "How to setup your computer" section indicates the necessary setup for the simulator.  This is referenced in the first step of the lab.
