### ISSUE TITLE
Meraki module | can't set "Scanning API enabled"

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#203]
On this page https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-03-location-scanning-python/step/3 see 
`1. Login to the DevNet Sandbox and select the lab Meraki Small Business or Meraki Enterprise. Follow the instructions to make a reservation and continue with the next step once you've logged into Meraki.`

`2. Under Network, select Network-wide->General.`

`3. Scroll down to Location and Scanning and verify the API is enabled.`

Using Sandbox Meraki Enterprise
Go to Location and scanning -> Set Scanning API from Scanning API disabled to Scanning API enabled

Click on another menu item and see browser alert:
"Leave site?
Changes you made may not be saved."
How this information can be saved? Can't find the save button.

**Comment by denapom11** [comment]
This issue has been addressed with several updates to the labs in December 2019.  "How to setup your computer" section indicates the necessary setup for the simulator.  This is referenced in the first step of the lab.

**Comment by denapom11** [comment]
LL no longer uses sandbox
