### ISSUE TITLE
Meraki module | MV devices in network

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#205]
On this page https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-08-mv-sense/step/1
I found and save to variable "the id of the reserved network (it will be the one with your email address appended to the name)"
But using GET request {{baseUrl}}/networks/{{networkId}}/devices I receive blank JSON.

Also, the same issue https://github.com/CiscoDevNet/learning-labs-issues/issues/200

**Comment by oborys** [comment]
When using Meraki Enterprise Sandbox

**Comment by denapom11** [comment]
This issue has been addressed with several updates to the labs in December 2019.
