### ISSUE TITLE
Meraki module | Meraki MV Sense

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#206]
On this page https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/meraki-08-mv-sense/step/2 chapter "Identify the camera serial" note that algorithm correct for "DNENT3-chrlunsf@cisco.com" network, in case if we use Meraki Enterprise Sandbox.

**Comment by denapom11** [comment]
This issue has been addressed with several updates to the labs in December 2019.
