### ISSUE TITLE
Meraki module | ZIP alexaMeraki-guestwifi Repo

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#207]
On this page https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/Meraki_Alexa/step/3
On this stage 
```
Now, on your local machine, create a ZIP package:

// cd into the directory
cd alexaMeraki-guestwifi-master
// zip
zip -r lambda_function.zip *
```
Instead of the block above, I suggest write sentences: 
"Go to alexaMeraki-guestwifi Repo (https://github.com/CiscoDevNet/alexaMeraki-guestwifi) click "Clone or download" then choose "Download ZIP."
than is unified way to all environments (Mac/Linux/Windows)

**Comment by annegentle** [comment]
Fixed and published; closing.
