### ISSUE TITLE
Meraki module | cameras integrated in an ACI fabric

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#208]
On this page https://developer.cisco.com/learning/lab/learning-labs-aci-meraki/step/2
When I go through "Step 2. Login to the APIC controller" 
can't open this page https://apic.cisco.local/
we need a link on the Sandbox APIC controller and credential for it.
So without this, I can't go through the next steps.

In "Step 1. Check Meraki dashboard" when I opened https://account.meraki.com/secure/login/dashboard_login
and sign-in with credential ciscodevnet01@gmail.com / cisco123
I saw "This network has been disabled for non-payment. Please contact Meraki Sales for assistance.". It's good to notice that it's ok to navigate to the camera, these features are working, am I right?

**Comment by denapom11** [comment]
please remove this lab

**Comment by dethanga** [comment]
@denapom11 and cc @annegentle 
This Lab is deactivated. Hence I am closing this issue. 
The same issue is duplicated to #209 
Thanks - Devi
