### ISSUE TITLE
Meraki module | aci-meraki lab redirection and menu items

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#209]
After finished this lab https://developer.cisco.com/learning/lab/learning-labs-aci-meraki/step/4
I suggest redirected to next relevant Lab https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/learning-labs-aci-meraki-api/step/1
For now users redirected to https://developer.cisco.com/learning/labs

And in both LL it's better to make a more detailed menu items instead of "Page 1, Page 2, etc".

**Comment by denapom11** [comment]
please remove lab

**Comment by annegentle** [comment]
Thanks Matt (@denapom11)! It's learning-labs-aci-meraki Lab ID that should be removed? Any Lab ID to redirect to?

**Comment by dethanga** [comment]
@denapom11 and cc @annegentle 

This issue is dependent on #208 (this was already closed with comments).

Hence I am closing this too.

Thanks - Devi
