### ISSUE TITLE
Meraki module | apic.cisco.local doesn't work

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#210]
On this LL https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/learning-labs-aci-meraki-api/step/1
links below are unavailable:
https://apic.cisco.local/
https://apic.cisco.local/doc/html/

**Comment by annegentle** [comment]
Yeah, these aren't real links unless you're in a certain environment, as stated in the "Bring Your Own Computer" link. I'll close.
