### ISSUE TITLE
Links incorrect for Pyats and Genie documentation 

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#216]
The Labs in the PyATS module point to a pubhub link rather than a developer.cisco.com link for their documentation. So the links go to a broken S3 bucket when they move: https://pubhub.devnetcloud.com/media/pyats-packages/docs/genie/robot/index.html is broken.

For example, https://pubhub.devnetcloud.com/media/pyats/docs/robot/index.html I think they're doing it due to the iframed solution, such as https://developer.cisco.com/docs/pyats-getting-started/. 

Another iframed one is https://developer.cisco.com/docs/pyats/api/. 

https://developer.cisco.com/learning/modules/pyats-genie

**Comment by klevenstein** [comment]
Resolved in https://github.com/CiscoDevNet/pyats-labs/releases/tag/1.2
