### ISSUE TITLE
No titles in JSON file for ansible-02_ansible-intro

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#218]
Sidebar TOC shows Page 1, Page 2, etc. Add titles to the JSON file.

**Comment by annegentle** [comment]
I added you to the "Git" in LL.

**Comment by dethanga** [comment]
Added the file names in the JSON file and corrected the tags. Published to staging:
https://testing-developer.cisco.com/learning/lab/ansible-02_ansible-intro/step/1

I am closing this issue.

Thanks,
Devi
