### ISSUE TITLE
Sandbox related updates for "Getting Hands On with Ansible"

### ISSUE THREAD

**Issue by smupad** [CiscoDevNet/learning-labs-issues#220]
**Learning lab**: Getting Hands On with Ansible (https://developer.cisco.com/learning/lab/ansible-03_ansible-hands-on/step/1) 

**Section**: Step 1. Setting Up and Verifying Ansible Infrastructure

1. Update credentials for CentOS DevBox to **developer/C1sco12345**  (old creds were root/Admin_1234!)
2. There appear to be duplicates for the "connect to CentOS DevBox" output? Delete duplicate. 
3. Step "pip install ansible==2.2"may not work given security posture updates. Recommendations are made in this forum post - https://community.cisco.com/t5/devnet-sandbox/issue-with-open-nx-os-with-nexus-9kv-sandbox/m-p/3948370#M4081

Learning lab needs to be tested to ensure working after these changes.

**Comment by dethanga** [comment]
@annegentle 
Thanks for reviewing and approving my PR. 
Here is the published link: https://developer.cisco.com/learning/lab/ansible-03_ansible-hands-on/step/1
@smupad - I have verified the changes, all looks fine and got the expected output. 
I am closing this issue.

Thanks,
Devi
