### ISSUE TITLE
Remove pygraphiz from sbx-intro-aci-03_aci-toolkit and add Python 3

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#221]
I tested on Python 3.7.5 and everything looks good.  However, there is one lab that uses pygraphviz package to generate aci-diagram that doesn’t work because pygraphiz only available for Python 2.7, we may need to remove that from the lab.
                  https://developer.cisco.com/learning/tracks/aci-programmability/intro-to-aci/sbx-intro-aci-03_aci-toolkit/step/4
(Exercise 3).

**Comment by movinalot** [comment]
I have determined the way to install pygraphviz on CentOS, Windows and MAC OS for Python 3.7.5 and have updated labs accordingly.
