### ISSUE TITLE
RSS is now a bot, no longer integration => collab-business-conf-spark-integration-itp

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#225]
From the Collab DNE track:

**Lab:** Configure a Webex Teams integration
**Lab ID:** collab-business-conf-spark-integration-itp
**Page:** Page 2 - Configure an RSS feed integration

The RSS app is no longer an integration, rather it is simply a bot.

Therefore, the workflow to add an RSS feed to your Webex Teams space differs from the lab guide.

Once you add the RSS integration to your space, you need to switch over to Webex Teams, mention the bot (using the ‘@’ symbol) with the ‘manage’ keyword:
![Picture1](https://user-images.githubusercontent.com/15103735/73343151-5951c680-4280-11ea-90df-6c0d4f2cad01.png)

It will then create a new space in your list:
![Picture2](https://user-images.githubusercontent.com/15103735/73343220-7ab2b280-4280-11ea-9c2c-23c1feff6375.png)

Then it sends you a message with a URL to take you to the management page:
![Picture3](https://user-images.githubusercontent.com/15103735/73343239-87cfa180-4280-11ea-8f0e-5eb3ace9ef60.png)

Lab instructions and screenshots need updated to reflect.

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/business-value-itp/collab-business-conf-spark-integration-itp/step/2

**Comment by dethanga** [comment]
@vvaliapa 
This issue is referenced with #226, please update the Lab instructions and screenshots.

Thanks,
Devi

**Comment by vvaliapa** [comment]
Updated the "Configure an RSS feed integration" page. Here is the updated Lab:  https://developer.cisco.com/learning/lab/collab-business-conf-spark-integration-itp/step/1
