### ISSUE TITLE
Cannot disconnect RSS integration  => collab-business-conf-spark-integration-itp

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#226]
From the Collab DNE track:

**Lab:** Configure a Webex Teams Integration
**Lab ID:** collab-business-conf-spark-integration-itp
**Page 3:** Disconnect the integration

#225 references the lab guide steps needing updated on Page 2 when adding the Bot.

Now, for this issue, on **Page 3: Disconnect the integration**
These steps don't need done at all since we are using a bot instead of an integration.

Lab guide needs updated to remove these extra/unnecessary steps.

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/business-value-itp/collab-business-conf-spark-integration-itp/step/3

**Comment by vvaliapa** [comment]
Removed Page 3: Disconnect the integration.
Here is the updated Lab:  https://developer.cisco.com/learning/lab/collab-business-conf-spark-integration-itp/step/1
