### ISSUE TITLE
Navigation instructions to find Access token need clarified => collab-business-sparksdk-widgets-itp

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#227]
From the Collab DNE track:

**Lab:** Experiment Audio/Video Calling & Messaging with Webex Teams Widgets
**Lab ID:** collab-business-sparksdk-widgets-itp
**Page:** Page 2 – Experience the ‘Space’ Widget 

Lab guide steps are unclear because if you click **Documentation** and scroll down, you cannot see the access token.
* Current steps state: _"Next, click Docs and then scroll down to see your developer access token."_

Should add a statement in the lab guide mentioning clicking on "Getting Started".
* e.g. _"Next, click Docs > Getting Started and then scroll down to see your developer access token."_

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/business-value-itp/collab-business-sparksdk-widgets-itp/step/2

**Comment by dstaudt** [comment]
Fixed in https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/414d7e3d6bdbd5eea77b5e56f74de9689983efd1
