### ISSUE TITLE
Sample HTML code needs updated for 0.2.3.4 of space widget => collab-business-sparksdk-widgets-itp

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#228]
From the Collab DNE track:

**Lab:** Experiment Audio/Video Calling & Messaging with Webex Teams Widgets
**Lab ID:** collab-business-sparksdk-widgets-itp
**Page:** Page 3 – Add the Widget to an HTML page

Because of the breaking changes in 0.2.3.4 of space widgets, `data-to-person-email=phil@smith.com` given in the sample HTML code in the lab guide is no longer valid. Looking at new Widget Example Code, we can see the “To” destination is now split onto 2 lines, one for “id” and one for “type”.

The correct code to copy/paste, then modify, would be:
```
<html>
  <head>
    <meta charset="utf8">
    <title>Space Widget Demo</title>
    <link rel="stylesheet" href="https://code.s4d.io/widget-space/production/main.css">
  </head>
  <body>
    <div style="width: 500px; height: 500px;"
        data-toggle="ciscospark-space"
        data-access-token="YOUR_ACCESS_TOKEN"
        data-destination-id="DESTINATION_ACCOUNT_EMAIL"
        data-destination-type="email"
     />
    <script src="https://code.s4d.io/widget-space/production/bundle.js"></script>
  </body>
</html>
```

Sample HTML code needs updated in lab guide (with above).
Screenshot of Widget Example Code needs updated in lab guide as well.

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/business-value-itp/collab-business-sparksdk-widgets-itp/step/3

**Comment by dstaudt** [comment]
Fixed in https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/414d7e3d6bdbd5eea77b5e56f74de9689983efd1
