### ISSUE TITLE
Old product names need updated (Spark and APIC-EM) => collab-spark-overview-rest

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#229]
From the Collab DNE track:

**Lab:** Overview of REST APIs
**Lab ID:** collab-spark-overview-rest
**Page:** Page 2 – What is a REST Web Service?

The third diagram on the page references **Cisco Spark / Spark Server**. Diagram should either be updated to say Webex Teams or add a statement reminding that it’s the previous name to Webex Teams.

Also, there is a separate, dated, reference to **APIC-EM** (which is no longer being sold by Cisco) further down the page and should be updated to DNA Center.

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/automating-spark-itp/collab-spark-overview-rest/step/2

**Comment by dstaudt** [comment]
Fixed in https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/10f787e3e7934e17b63c01a2bf7b9580252affef
