### ISSUE TITLE
Add Python venv steps to "How To Setup Your Own Computer" => collab-spark-interfacing-with-rest

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#230]
From the Collab DNE track:

**Lab:** Generating Python Webex Teams API code using Postman
**Lab ID:** collab-spark-interfacing-with-rest
**Page:** How to Setup Your Own Computer

Recommend adding steps to use a Python virtual environment (let's get people using best practices!)

e.g. _"While not explicitly specified, it is always a good idea to use a separate python virtual environment for each project, due to the fact that each project/codebase may have different dependencies."_

Instructions should be added for Windows (CMD) and Windows (Git-Bash) since both are commonly used in the DNE pods. MacOS instructions could be added as well for good measure.

**Windows (CMD):**
```
C:\Users\ntruncik>cd coding
C:\Users\ntruncik\coding>md collab-learning-labs
C:\Users\ntruncik\coding>cd collab-learning-labs
C:\Users\ntruncik\coding\collab-learning-labs>py -3 -m venv myvenv
C:\Users\ntruncik\coding\collab-learning-labs>myvenv\Scripts\activate
(myvenv) C:\Users\ntruncik\coding\collab-learning-labs>python -V
Python 3.8.1
(myvenv) C:\Users\ntruncik\coding\collab-learning-labs>pip3 install requests
<output omitted>
```

**Windows (Git Bash):**
```
ntruncik@NTRUNCIK-C31DD MINGW64 ~
$ cd coding/
ntruncik@HOST MINGW64 ~/coding
$ mkdir collab-learning-labs
ntruncik@HOST MINGW64 ~/coding
$ cd collab-learning-labs/
ntruncik@HOST MINGW64 ~/coding/collab-learning-labs
$ py -3 -m venv myvenv
ntruncik@HOST MINGW64 ~/coding/collab-learning-labs
$ source myvenv/Scripts/activate
(myvenv)
ntruncik@HOST MINGW64 ~/coding/collab-learning-labs
$ python -V
Python 3.8.1
(myvenv)
ntruncik@HOST MINGW64 ~/coding/collab-learning-labs
$ pip3 install requests
<output omitted>
```

**MacOS:**
```
HOST:coding ntruncik$ mkdir collab-learning-labs
HOST:coding ntruncik$ cd collab-learning-labs
HOST:collab-learning-labs ntruncik$ python3 -m venv myvenv
HOST:collab-learning-labs ntruncik$ source myvenv/bin/activate
(myvenv) HOST:collab-learning-labs ntruncik$ 
(myvenv) HOST:collab-learning-labs ntruncik$ python -V
Python 3.8.1
(myvenv) HOST:collab-learning-labs ntruncik$ pip3 install requests
<output omitted>
```

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/automating-spark-itp/collab-spark-interfacing-with-rest/step/1

**Comment by dstaudt** [comment]
Fixed in https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/0304ef4c7a7775d17f40cd16453f8236a8efe3c9
