### ISSUE TITLE
Sample code has leading space which leads to errors when copy/pasting => collab-spark-interfacing-with-rest

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#231]
From the Collab DNE track:

**Lab:** Generating Python Webex Teams API code using Postman
**Lab ID:** collab-spark-interfacing-with-rest
**Page:** Page 3 – Writing a Python Script

Sample code on this page has a leading space on each line, which when copy/pasted will break Python.

Ideally, the sample code should be updated to remove this leading space. This will create the least errors and confusion.

Alternately, add a short statement letting participants know.

e.g. _Although typing the code out yourself is the best way to learn programming, if you choose to copy/paste from the DevNet Learning Lab then be careful that it may copy a space in front of some of the lines of code:_
![Picture4](https://user-images.githubusercontent.com/15103735/73347559-185db000-4288-11ea-99bc-716819e5f46c.png)
![Picture5](https://user-images.githubusercontent.com/15103735/73347564-1b58a080-4288-11ea-9ac5-7542a3221553.png)
_You will need to delete those extra spaces after you Paste the code._

Removing the leading space would be the simplest solution and save valuable troubleshooting time.

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/automating-spark-itp/collab-spark-interfacing-with-rest/step/3

**Comment by dstaudt** [comment]
Can't see anything in the lab source that would cause this, it's lined up as best the tools will allow (perhaps a browser issue?) - perhaps it was fixed previously?  Closing
