### ISSUE TITLE
Add Python venv steps to "How To Setup Your Own Computer" => collab-spark-calling-apis-from-python-itp

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#232]
From the Collab DNE track:

**Lab:** Building Python Requests to Read and Create Webex Teams API Items
**Lab ID:** collab-spark-calling-apis-from-python-itp
**Page:** How to Setup Your Own Computer

Steps should be updated to show using a Python virtual environment.

Similar to #230 but for a different lab - while it’s not explicitly specified, it is always a good idea to use a separate python virtual environment for each project. In this case, the participant can continue using the one they created earlier.

Or, if the participant is starting from this lab and has not previously completed "Generating Python Webex Teams API code using Postman" (collab-spark-interfacing-with-rest), instructions should be given to correctly create a venv. See #230 for an example.

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/automating-spark-itp/collab-spark-calling-apis-from-python-itp/step/1

**Comment by dstaudt** [comment]
Fix in https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/5a70fc06b2d0d287009cfb39bf2cd160318ba03f
