### ISSUE TITLE
Add Python venv steps to "How To Setup Your Own Computer" => collab-spark-chatops-bot-itp

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#234]
From the Collab DNE track:

**Lab:** Chat-Ops with Webex Teams and Python
**Lab ID:** collab-spark-chatops-bot-itp
**Page:** How to Setup Your Own Computer

Steps should be updated to show using a Python virtual environment.

Similar to #230 but for a different lab - while it’s not explicitly specified, it is always a good idea to use a separate python virtual environment for each project. In this case, the participant can continue using the one they created earlier.

Or, if the participant is starting from this lab and has not previously completed "Generating Python Webex Teams API code using Postman" (collab-spark-interfacing-with-rest), or "Building Python Requests to Read and Create Webex Teams API Items" (collab-spark-calling-apis-from-python-itp), instructions should be given to correctly create a venv. See #230 for an example.

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/automating-spark-itp/collab-spark-chatops-bot-itp/step/1

**Comment by dstaudt** [comment]
Fix in https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/97dc476450f750870e5c7d5fb8635614e2cc6321#diff-5695d70fdd1ad90def6876d1e63494fe
