### ISSUE TITLE
Steps need added to prevent an error from occurring => collab-spark-extensibility-itp

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#238]
From the Collab DNE track:

**Lab:** Explore Webex Teams Extensibility Approaches and Platforms
**Lab ID:** collab-spark-extensibility-itp
**Page:** Page 3 – ‘Push’ apps

Steps need added to the lab guide to prevent an error from occurring.

The error _"cannot be loaded because running scripts is disabled on this system"_ comes up when users try to run the **up_ps.ps1** PowerShell script. This will happen to all Windows users who have not done the following workaround.

In order to run the up_ps.ps1 PowerShell script, users need to first enable running unsigned scripts by entering (from an Administrator-level terminal window): `set-executionpolicy remotesigned`.

![Picture7](https://user-images.githubusercontent.com/15103735/73359231-a180e100-42a0-11ea-9d81-97db9063fe2a.png)

This only ever needs done once on a workstation, but it's very possible users haven't done this prior, so instructions should be added.

https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/spark-extensibility-itp/collab-spark-extensibility-itp/step/3

**Comment by dongosselin** [comment]
I've updated the page with a note.
