### ISSUE TITLE
Need to add Class C subnet

### ISSUE THREAD

**Issue by adrienne-at-work** [CiscoDevNet/learning-labs-issues#239]
https://developer.cisco.com/learning/lab/networking-103-IP-addresses/step/4
Need to add class C subnet
Class C: 192.168. 0.0 to 192.168. 255.255

**Comment by dethanga** [comment]
@klevenstein 

I have added the Class C type IP address and made few minor edits to the files
Please verify and approve. Thanks!

Raised PR: https://github.com/CiscoDevNet/networking-series-learning-labs/pull/28

Regards,
Devi

**Comment by dethanga** [comment]
@klevenstein and cc @annegentle 

The changes are posted to production. 
https://developer.cisco.com/learning/lab/networking-103-IP-addresses/step/4

As informed, I am closing this issue.

Thanks,
Devi
