### ISSUE TITLE
Recommended developer environment install does not include the Atom IDE

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#240]
Adding the Atom IDE would be useful for GitHub integrations and the like. A Fundamentals course user suggested it.

**Comment by annegentle** [comment]
The LL in this module: https://developer.cisco.com/learning/modules/dev-setup/dev-what/step/1 describe Atom setup for each operating system. @klevenstein  has a list of Atom plugins she uses to create a terminal window inside of Atom, I think that might be a good start to work on this.

**Comment by klevenstein** [comment]
Here's what I'm using; we could present it as "suggested, not required, feel free to search for your own":

platformio-ide-terminal
https://atom.io/packages/platformio-ide-terminal 
Enables you to open a terminal window within Atom

atom-ide-ui
https://atom.io/packages/atom-ide-ui
Supports language services, linting, and debugging for different languages. A prerequisite for related language-specific packages. 

ide-json
https://atom.io/packages/ide-json
Support for JSON

ide-python
https://atom.io/packages/ide-python
Support for Python

**Comment by vvaliapa** [comment]
Closing this issue as won't fix.
