### ISSUE TITLE
Docker installation instructions on Windows in dev-win Lab

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#241]
User reports that the dev-win LL points to Docker CE but the link goes to Docker Desktop. Looks like the product offering has changed. Change the Learning Lab if Windows must have Docker Desktop instead. Point to https://docs.docker.com/docker-for-windows/install/ as deeper more detailed install instructions.

Pasting the customer input below, but it turned out virtualization was off in the BIOS. This is a common problem with Windows and Docker. The user reports, "After turning it on, docker now runs and I could continue with the setups."

Also in our LL, add a link to the Docker troubleshooting page at https://docs.docker.com/docker-for-windows/troubleshoot/.

---
I am running the steps in Setting up your Windows workstation as a development environment at link https://developer.cisco.com/learning/lab/dev-win/step/8
I am at step 7, which is to install and test Docker
The download link takes me to installation of "Docker Desktop for Windows" and not "Docker CE for Windows".
I have now installed "Docker Desktop for Windows"
After this I am trying to test with GIT using the steps from the link but get the below output :

$ docker run busybox
C:\Program Files\Docker\Docker\resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

Is it the wrong docker installation, or am I missing something?

**Comment by dethanga** [comment]
@klevenstein 
As per Anne's instructions, I have incorporated the changes. Raised PR - Please review.
https://github.com/CiscoDevNet/dev-setup-labs/pull/24

Thanks,
Devi
