### ISSUE TITLE
Devnet Associate - Parsing json w/ python hates self-signed certs

### ISSUE THREAD

**Issue by pkillur** [CiscoDevNet/learning-labs-issues#242]
On step 2 for handling JSON with python - two things exist.   First is that it's calling python (not python3 on a mac) and that if one uses python3 as the lab instructs python3 freaks out about a self-signed cert.  Throwing the bottom text into the .py script fixes the issues:

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

**Comment by klevenstein** [comment]
Hi @pkillur - can you provide a link to where this issue appears?

**Comment by pkillur** [comment]
My bad - 

https://developer.cisco.com/learning/lab/coding-202-parsing-json/step/1
Step 5 when you invoke the python script.  The .py has no way to handle the self-signed cert.

**Comment by klevenstein** [comment]
Addressed in https://github.com/CiscoDevNet/coding-series-learning-labs/pull/84.

**Comment by klevenstein** [comment]
Published; closing
