### ISSUE TITLE
Meraki DNE: Intro-to-Python Part 1 - add Meraki as a track

### ISSUE THREAD

**Issue by cskoglun** [CiscoDevNet/learning-labs-issues#243]
In Intro-to-Python Part 1, please add Meraki as a DNE track under Step 1 and also somehow we need to highlight that this step has already been done. Today it says:

"You cloned one of these repositories to your computer as part of the "Using Git to Copy Code and Setting Up the Local Environment"

This is not enough for the attendees. We need to make it bold and be really clear that during a DevNet Express event, this is a step that is already done. 

The issue is that the attendees start cloning the repos of other tracks and get lost in the labs, and we need to spend a lot of time guiding them to the correct repository.

**Comment by klevenstein** [comment]
Updated and published; closing.
https://developer.cisco.com/learning/lab/intro-python-part1/step/1
