### ISSUE TITLE
ansible-03_ansible-hands-on/step/1 - can't complete lab due to the fact that the host can't reach the internet due to the updated rules for SANDBOXES (git clone is required)

### ISSUE THREAD

**Issue by ghost** [CiscoDevNet/learning-labs-issues#245]
Learning lab: Getting Hands On with Ansible (https://developer.cisco.com/learning/lab/ansible-03_ansible-hands-on/step/1)

With Step 1. Setting Up and Verifying Ansible Infrastructure the last task that you need to do is (git clone https://github.com/DevNetSandbox/sbx_nxos) but since the host can't reach the internet due to the updated policy this will never be possible.

Permanent solution:
1) Include the directory into the CentOS DevBOX in the future and edit the lat tasks to reflect that.
2) Have a repository hosted on a server that is reachable from the host side.

Workaround that I did to be able to continue with the lab:
1) Installed the directory/reprository from GitHub.
2) Connect to the lab via Anyconnect and then move the files into the CentOS DevBOX using a scp client (used WinSCP); since scp is installed on the box. 
3) Move the file into venv directory and after that continue with the lab tasks.

Severity 2: workarounds. the lab or module works but is very inconvenient or confusing

**Comment by annegentle** [comment]
Lab has been deactivated.

**Comment by annegentle** [comment]
Related to https://github.com/CiscoDevNet/learning-labs-issues/issues/220

**Comment by klevenstein** [comment]
Closing this issue since the lab has been deactivated;  reopen if needed.
