### ISSUE TITLE
Updates to "Reserving UCS C480ML Sandbox" Learning lab

### ISSUE THREAD

**Issue by smupad** [CiscoDevNet/learning-labs-issues#246]
**Background**: The "UCS C480ML with NVIDIA GPU Cloud" sandbox URL has changed. It needs to be updated in the Learning lab. 

New sandbox URL is:  https://devnetsandbox.cisco.com/RM/Diagram/Index/2fff8794-1adc-48c5-b8e1-781cca152cb3?diagramType=Topology

**Affected Learning lab**: Reserving UCS C480ML Sandbox - https://developer.cisco.com/learning/lab/c480-sandbox/step/1 

**Updates required**: 
Under "Step 3: Find the C480ML Sandbox" :
I.	Update the URL in "The direct link to the UCS C480ML sandbox can be found here". 

II.	Update the screenshots. They now show the Collaboration category and "Cisco Webex Meetings". Should be replaced with screenshots of sandboxes in “Data Center” category and the UCS C480ML with NVIDIA GPU Cloud sandbox page.   
 
III.	Under "Select a Date & Time" update line "...Sandbox with 8x Nvidia Tesla v100 GPUs will be available for a maximum 48 hour reservation." to say something like "...Sandbox with 8x Nvidia Tesla v100 GPUs will be available for a maximum 24 hour reservation."

**Comment by vvaliapa** [comment]
Fixed the issue, here is the updated link: https://developer.cisco.com/learning/lab/c480-sandbox/step/1
