### ISSUE TITLE
Updates to "Machine Learning with the UCS C480ML" Learning lab

### ISSUE THREAD

**Issue by smupad** [CiscoDevNet/learning-labs-issues#247]
**Background**: The "UCS C480ML with NVIDIA GPU Cloud" sandbox URL has changed. It needs to be updated in the Learning lab.

New sandbox URL is: https://devnetsandbox.cisco.com/RM/Diagram/Index/2fff8794-1adc-48c5-b8e1-781cca152cb3?diagramType=Topology

Affected Learning lab: Machine Learning with the UCS C480ML - https://developer.cisco.com/learning/lab/c480-ngc-101/step/1 

**Required updates**:
Under “Access Sandbox - Connect to the UCS C480ML with Nvidia GPU Cloud Sandbox”, update sandbox URL to point to  https://devnetsandbox.cisco.com/RM/Diagram/Index/2fff8794-1adc-48c5-b8e1-781cca152cb3?diagramType=Topology

**Comment by vvaliapa** [comment]
Updated the fix, here is the updated Lab link: https://developer.cisco.com/learning/lab/c480-ngc-101/step/1
