### ISSUE TITLE
Update "Cisco IoT Design-in Industrial Automation Learning Lab" 

### ISSUE THREAD

**Issue by smupad** [CiscoDevNet/learning-labs-issues#248]
**Background**: The "Industrial Networking Sandbox" sandbox URL has changed. It needs to be updated in the Learning lab.

**New sandbox URL** is: https://devnetsandbox.cisco.com/RM/Diagram/Index/097310ec-afbe-4e8b-8611-87fe2a087e1c?diagramType=Topology

Affected Learning lab: Cisco IoT Design-in Industrial Automation Learning Lab - https://developer.cisco.com/learning/lab/industrial-automation-lab/step/1

**Required updates**:
1. Under "Reserve the Cisco Industrial Router Sandbox" step 1, update the sandbox URL . 
2. Review rest of the steps/content to make sure it aligns with sandbox details. Test as required.

**Comment by vvaliapa** [comment]
Updated the new sandbox link and tested the Lab with a new sandbox.
Here is the updated link: https://developer.cisco.com/learning/lab/industrial-automation-lab/step/1
