### ISSUE TITLE
learning-labs-aci-meraki broken link

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#250]
After finish this lab https://developer.cisco.com/learning/lab/learning-labs-aci-meraki/step/4 in dialog window this link "Go to next lab" is broken. Redirect to this url https://developer.cisco.com/learning/lab/aci-101-apic-interfaces/step/1 - Lab not found.
I think correct url is https://developer.cisco.com/learning/tracks/meraki/getting-started-with-meraki/learning-labs-aci-meraki-api/step/1
screen - https://ibb.co/rfNksMR

**Comment by annegentle** [comment]
Hi @oborys - I noticed this same problem in your PR at https://github.com/CiscoDevNet/learning-labs-aci-meraki/pull/4/files. You can change it by updating the JSON file to point to the correct "next" links. Let us know if you don't know where that section is in the JSON or which Lab IDs to use.

**Comment by denapom11** [comment]
please remove this lab

**Comment by annegentle** [comment]
This Lab has been removed, closing Issue.
