### ISSUE TITLE
DNA Northbound API Python Script functions broken

### ISSUE THREAD

**Issue by pkillur** [CiscoDevNet/learning-labs-issues#251]
Hey team - seeing that this script under "Putting it all together" won't run when you create it and run in a virtual environment.  When I manually diff'd between what is laid out section by section, I noticed that line 81 in the 'all together' section has **if name == "main"**.  Looking above the section it should be 

> **if __name__ =="__main__** - (please note - there should be underbars - git forum is stripping these off for some reason).  Otherwise it bails at line 81

URI:
https://developer.cisco.com/learning/lab/dnav3-dnac-nbapi-hello-world/step/6
Name/ Title:
DNA Northbound API
Step:
6

**Comment by annegentle** [comment]
Is it the one below the "Complete Python Script" where you click the triangle to expand? It looks like a rendering bug, thanks for reporting. The source is correct, the HTML output is stripping the double underbars.
<img width="612" alt="Screen Shot 2020-04-14 at 5 47 04 PM" src="https://user-images.githubusercontent.com/501981/79282342-8d4d8880-7e7a-11ea-948e-ac1f41a5c46a.png">

**Comment by klevenstein** [comment]
So, two things. One is that the DNA DNE track has been updated, with a completely overhauled DNA Center module (here)[https://developer.cisco.com/learning/devnet-express/dnav4-track]. However, I see that the `__main__` rendering bug appears there as well, so this is definitely something we need to figure out how to fix.

**Comment by annegentle** [comment]
Yeah - since this is a platform bug, the only alternative content-wise would be a screenshot of the code. Thoughts?

**Comment by pkillur** [comment]
Can we maybe link to a text file that pops open in a new frame or window? 
That might solve the problem maybe.  A screenshot would quite honestly be just
as bad if not more frustrating - at least from my perspective as someone doing
the labs!







On Tue, May 26, 2020 9:52 PM, Anne Gentle notifications@github.com  wrote:


Yeah - since this is a platform bug, the only alternative content-wise would be
a screenshot of the code. Thoughts?

**Comment by klevenstein** [comment]
Lab has been superseded and no longer exists; closing.
