### ISSUE TITLE
intro-python-part2 : python >3.7 dict order preservation clarification 

### ISSUE THREAD

**Issue by arussu** [CiscoDevNet/learning-labs-issues#252]
This is regarding the following note about dictionaries in `Step 1: Native Python data structures` step of the lab:
![image](https://user-images.githubusercontent.com/16317827/80356827-5617a800-887a-11ea-92dd-d3849c076190.png)

Some clarifications are required to avoid confusion regarding dictionary order of insertion preservation in python versions >= 3.7.
As per https://docs.python.org/3/whatsnew/3.7.html#summary-release-highlights :
![image](https://user-images.githubusercontent.com/16317827/80357082-b9093f00-887a-11ea-8a5f-84106adba700.png)

Also in official python docs (https://docs.python.org/3.7/library/stdtypes.html#typesmapping):
![image](https://user-images.githubusercontent.com/16317827/80357156-d3431d00-887a-11ea-8b46-294c773c0c89.png)

Thank you

**Comment by annegentle** [comment]
@arussu Can you suggest specific revisions to avoid confusion?

**Comment by arussu** [comment]
@annegentle We could say:
"""
Note: Up to python 3.6 the dictionaries key-value pairs were stored in unordered fashion. Python 3.6 introduced order of insertion preservation which has been declared to be an official part of the Python language spec in Python 3.7 and later.
"""

**Comment by annegentle** [comment]
Thanks, fixed and published.
