### ISSUE TITLE
Titles in "next" Lab JSON are inaccurate

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#254]
Reported through DevNet support:

I'm having issues with some of the DevNet modules/labs. I'm trying to do the Network Controllers module. I have completed the Network Devices lab. The next lab is "Cisco DNA Center APIs with Python: Part 1 - The Basics", when I click on that lab I go to the "Cisco DNA Center API Overview" lab which doesn't have anything to do with Python. If I complete this lab, and go to the next lab "Cisco DNA Center APIs with Python: Part 2 - Path Trace" I get " Lab Not Found. Please try a different lab". So how do I get to the "Cisco DNA Center APIs with Python: Part 1 - The Basics" lab? The the issue of missing labs isn't just with this particular lab, the problem seems more widespread, e.g. after I finish the "Cisco DNA Center Platform - Template Programmer" lab and choose to go to the next lab "Introduction to Cisco DNA Center REST APIs" nothing happens.

**Comment by annegentle** [comment]
Thank you for your quick response.  In the case of the "Network 
Controllers" module after completing the

https://developer.cisco.com/learning/modules/net-controllers/network_device/step/4

lab the next lab is listed as

https://developer.cisco.com/learning/modules/net-controllers/dnac-basic/step/1

but what it goes to is

https://developer.cisco.com/learning/modules/net-controllers/dnav3-dnac-api-overview/step/1

when I finish this lab, the next lab is listed as:

https://developer.cisco.com/learning/modules/net-controllers/dnac-path-trace-archived/step/1

and this is when I get the "Lab not Found" error.

Also when I complete the

https://developer.cisco.com/learning/modules/network-programmability/dnav3-dnac-api-overview/step/8

lab and try to go the next lab nothing happens.  There is no link 
associated with the next lab.

The "Cisco DNA Center APIs with Python: Part 1 - The Basics" is part of 
2 modules, "Network Programmability" and "Network Controllers".  I can't 
complete the modules because it shows that I have not completed this lab.

**Comment by annegentle** [comment]
I think this Lab ID: dnav3-dnac-nbapi-hello-world has a circular reference with this Lab ID: dnav3-dnac-api-overview. You can't get "out" of the loop when you click the green arrow on each Lab's Summary page. Check the JSON file to see if there's a loop (one referring only to the other).

**Comment by klevenstein** [comment]
Here's the code in dnav3-dnac-nbapi-hello-world
``` "related": [
    {
      "labId": "dnav3-dnac-api-overview",
      "title": "Cisco DNA Center API Overview"
    },
    {
      "labId": "dnav3-dnac-nbapi-modules",
      "title": "Cisco DNA Center Northbound API Modules"
    },
    {
      "labId": "dnav3-dnac-nbapi-mission",
      "title": "Intro to Cisco DNA Center Mission"
    }
  ],
```

Here's what's in dnav3-dnac-api-overview, which has a self-referential "related" link:
```
  "related": [
    {
      "labId": "dnav3-dnac-api-overview",
      "title": "Cisco DNA Center API Overview"
    },
    {
      "labId": "dnav3-dnac-nbapi-hello-world",
      "title": "Cisco DNA Center Northbound API \"Hello Network\""
    },
    {
      "labId": "dnav3-dnac-nbapi-modules",
      "title": "Cisco DNA Center Northbound API Modules"
    },
    {
      "labId": "dnav3-dnac-nbapi-mission",
      "title": "Intro to Cisco DNA Center Mission"
    }
  ],
```

**Comment by annegentle** [comment]
See also https://github.com/CiscoDevNet/learning-labs-issues/issues/253 -

**Comment by klevenstein** [comment]
I've tried to test this out, but now it's showing me that I've completed the module and I can't reproduce the behavior.

**Comment by annegentle** [comment]
This one can't be reproduced; closing.
