### ISSUE TITLE
Byod.html file in 4-Umbrella-Investigate-API-Explained-v-1-1 has template text

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#256]
The byod.html file for https://developer.cisco.com/learning/lab/4-Umbrella-Investigate-API-Explained-v-1-1/step/1 has this text, replace with actual requirements; 

"To work on this lab with your computer, you need to meet the requirements listed here. If you need to write instructions for one operating system you can use class settings for `mac`, `windows`, or `linux` surrounding the text you want displayed for a particular operating system."

**Comment by annegentle** [comment]
@klevenstein this might be a DNE lab, you can move it to that tracking repo if you want.

**Comment by klevenstein** [comment]
The byod.html file here:
https://github.com/CiscoDevNet/dne-security-umbrella-labs/tree/master/labs/4-Umbrella-Investigate-API-Explained-v-1-1

should be revised to match the other byod.html files in the Umbrella module:
https://github.com/CiscoDevNet/dne-security-umbrella-labs

Should be fine to just copypaste the content from one of the correct ones into this one.

**Comment by klevenstein** [comment]
Here's a correct byod:
https://github.com/CiscoDevNet/dne-security-umbrella-labs/blob/master/labs/5-HandsOn-Investigate-API-Hunting-v-1-1/byod.html

**Comment by dethanga** [comment]
@klevenstein and cc @annegentle 
Thanks for sharing the info. I have copied the requirements; here is the updated Lab:
https://github.com/CiscoDevNet/dne-security-umbrella-labs/tree/master/labs/4-Umbrella-Investigate-API-Explained-v-1-1
I have also merged the changes to Master.
