### ISSUE TITLE
Ezpoll bot link is a 404 in the Mission: Experiment with the Ezpoll Bot Lab for DevNet Express for collab

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#257]
https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/spark-extensibility-itp/collab-spark-extensibility-mission-itp/step/1

This lab has a 404 in the first link to the Ezpoll bot. Probably should deactivate while debugging or replacing.

**Comment by annegentle** [comment]
@klevenstein or @dstaudt feel free to move this to the DevNet Express tracker.

**Comment by dstaudt** [comment]
Fixed in https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/5ca353ae2ea74abe7e708a8d7104ac423184e6da
