### ISSUE TITLE
Retest fnd-api-intro with reserved Sandbox 

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#260]
This Learning Lab still uses the `root` username, but it might still work. It was deactivated in Oct 2019 but should be retested to see if it works as documented.

**Comment by dethanga** [comment]
@annegentle and cc @klevenstein 
I have reserved the FND sandbox; able to access the "https://10.10.20.70/" using the "root" as user name,  through both SSH and GUI. 
Thanks - Devi

**Comment by dethanga** [comment]
@annegentle and @klevenstein 
Able to access the "FND sandbox" using "root".

Thanks - Devi
