### ISSUE TITLE
Docker LL needs retesting due to changes from Docker Hub requiring registration

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#262]
User reports that the instructions no longer work for one of the Docker LL due to a change on the Docker side, requiring registration.

Retest https://developer.cisco.com/learning/modules/cloud-native-development/docker-101/step/1 with current Docker requirements and update LL.

**Comment by annegentle** [comment]
It is the "play-with-docker" site that has the steps that now require login. Here are screenshots:
![04_29_15](https://user-images.githubusercontent.com/501981/92176166-88767a80-ee03-11ea-85c4-6fd367b0b247.jpg)
![04_30_23](https://user-images.githubusercontent.com/501981/92176218-a2b05880-ee03-11ea-869a-8dcb6eb00123.jpg)
![04_30_51](https://user-images.githubusercontent.com/501981/92176257-b360ce80-ee03-11ea-8911-17cbb844d36c.jpg)

**Comment by vvaliapa** [comment]
Updated the Lab and published.
