### ISSUE TITLE
User reports that the DevNet IMC Sandbox is not available but LL points to it in byod.html

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#263]
The LL in this repo: 
https://github.com/CiscoDevNet/ucs-imc-learning-labs

Still point to a Sandbox that is no longer available. Check with @movinalot to see what the plan is for these.

**Comment by dethanga** [comment]
@klevenstein and cc @annegentle 
Hi Karin, I have removed the "IMC Sandbox" instances for the Labs available in 
https://github.com/CiscoDevNet/ucs-imc-learning-labs/tree/master/labs
Here is the PR for review: https://github.com/CiscoDevNet/ucs-imc-learning-labs/pull/9
Kindly check.
Regards,
Devi

**Comment by klevenstein** [comment]
PR merged - closing
