### ISSUE TITLE
Spark still in diagram in DevOps module

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#265]
https://developer.cisco.com/learning/modules/devops/1-development/step/4 - @juliogomez do you have source files for these images so they can not say Spark?

**Comment by dethanga** [comment]
@annegentle  and cc @klevenstein 
I worked on the requested changes; provided my comments in the PR.
Here is the PR for your review, kindly check!
https://github.com/CiscoDevNet/devops-learning-labs/pull/25

**Comment by dethanga** [comment]
@annegentle and cc @klevenstein 

I have deactivated all the five Labs in "https://developer.cisco.com/learning/modules/devops".  Verified the Labs, after releasing and publishing. Currently, it is inactive and getting a "Lab Not Found" error. Thanks - Devi

**Comment by annegentle** [comment]
Thanks! Closing Issue.
