### ISSUE TITLE
Webex developer URLs have changed to use # 

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#266]
The Learning Labs with this link: 
 https://developer.webex.com/docs/api/getting-started/accounts-and-authentication 
need to be changed to:
 https://developer.webex.com/docs/api/getting-started#accounts-and-authentication 

In addition, any references to https://developer.webex.com/authentication.html should be changed to 
https://developer.webex.com/docs/api/getting-started#accounts-and-authentication

Here's a list of repos where this change should be made: 

https://github.com/CiscoDevNet/devnet-express-cloud-collab
https://github.com/CiscoDevNet/labs-cloud-collab
https://github.com/CiscoDevNet/collab-sparkwebhook
https://github.com/CiscoDevNet/intro-rest-labs
https://github.com/CiscoDevNet/collab-spark-auth-working

**Comment by annegentle** [comment]
You can use a list and checkmarks to help determine what repos are already done. Here's the state as of 9/23/20, the largest repo still needs the changes.

https://github.com/CiscoDevNet/devnet-express-cloud-collab
https://github.com/CiscoDevNet/labs-cloud-collab ✅ 
https://github.com/CiscoDevNet/collab-sparkwebhook ✅ 
https://github.com/CiscoDevNet/intro-rest-labs ✅ 
https://github.com/CiscoDevNet/collab-spark-auth-working ✅

**Comment by clifton-smith** [comment]
Fixed and Published
