### ISSUE TITLE
Coding and APIs Lab issues

### ISSUE THREAD

**Issue by MikeG500** [CiscoDevNet/learning-labs-issues#270]
I am going through the Coding and API lab but have encountered a couple of issues.  I asked a colleague to verify that they are seeing the same issues,and they are.   I  am running Mac OSx Catalina, 10.15.6. I have set up  my device as per the setup instructions in the initial lab page pop-up. First issue is in the lab:- What is REST? What are APIs, Step 4: Some REST API examples. The first few commands work ok but then I get a failure on the "draw cards" scenario in the Deck of Cards section. The attached "Terminal 1 screenshot" shows the commands from my Terminal used in the lab. There is also  a broken link  in the lab, highlighted in the attached "Broken Link" screenshot.  Next failure is in the WebEx Teams API section in Step 4, submitting the command to send the message to WebEx Teams returns a protocol error.  The next issue I had was in the lab:-  Getting started with REST APIs, Step 7, Hands on with cURL: client for URLs.  I was getting an intermittent error when submitting the request for Teams Rooms I am in.  The attached Terminal screen capture shows a successful response, but this was inconsistent tho it seems  to be working ok at the moment.  I spent too much time verifying that I was not doing something wrong.  I am now  going through the Postman section and it does seem to be working ok from Postman
<img width="1560" alt="Broken Link DevNet lab" src="https://user-images.githubusercontent.com/71716593/93904588-e820c100-fcf1-11ea-89d7-3f225e212da9.png">
<img width="1253" alt="Terminal 1 Screenshot" src="https://user-images.githubusercontent.com/71716593/93904617-f1119280-fcf1-11ea-956d-bfadede4b5bd.png">

Can you check these steps out and rectify if required?

Many thanks

Mike

**Comment by MikeG500** [comment]
A further issue in this lab is in the lab:- Hands On Exercise: Using Postman to Interact with REST APIs, Step 5 Using Postman to generate Code.  This lab is going ok  untilthe section near the bottom to run Python code.  There is a section see screenshot that advises the learner that they need to set up a Python environment  The explanation of how to do this is poor and the link to the Pythin Primer additional lab is broken.  This is a novice level learning.  I don't know what a Python Environment is, how to set it up or how to check if it is working correctly.   Dropping a single paragraph of this nature doesn't explain that therefore I am unable to progress any further.  Can you please look at this section through the eyes of a novice and provide a more detailed set of instructions on how to do this?
<img width="1540" alt="Screenshot 2020-09-22 at 17 35 18" src="https://user-images.githubusercontent.com/71716593/93911620-89ac1080-fcfa-11ea-95a0-f5d5e2668734.png">

**Comment by annegentle** [comment]
Hi, for the first item, it looks like the change from bash to zsh in the recent Catalina upgrade has caused the behavior to change and we'll update the LL. I'll investigate with a recently-updated Catalina Mac and get back to you. You can help me out by running these commands and letting me know the output in a comment here, that way I can replicate and test.

Run `bash --version` -- here's an example:

```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Run `zsh --version` -- here's an example:
```
$ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

Run `python --version` -- here's an example:
```
$ python --version
Python 3.8.5
```

Any intermittent error could be on the Webex server side, or in the identity service, so I can add a note that those are typically not the user's fault. What you describe is the way a developer's life goes - you can gain the confidence you need as you keep practicing, and keep asking good questions. 👍

**Comment by MikeG500** [comment]
Hi Anne

For bash version:


mgarvie@MGARVIE-M-F2LM /bin % bash --version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

Copyright (C) 2007 Free Software Foundation, Inc.



zsh:-



mgarvie@MGARVIE-M-F2LM /bin % zsh --version

zsh 5.7.1 (x86_64-apple-darwin19.0)

Copyright (C) 2007 Free Software Foundation, Inc.



Python:



mgarvie@MGARVIE-M-F2LM /bin % python --version

Python 2.7.16



I also have Python v3 installed



mgarvie@MGARVIE-M-F2LM ~ % python3 -V

Python 3.8.5



Hope this helps.  Can you also look into the broken links on the lab?



Regards



Mike

**Comment by annegentle** [comment]
Hi again, the links have been changed and the section re-written with more steps.

It seems your environment is fine. As an aside, we write instructions with `python` rather than `python3` since we don't know what the developer has by default in their system. If you can replicate again, let me know - I'll close this issue for now but please re-open if you can replicate the Protocol error (we can dig into that further including what your identity system is).

**Comment by MikeG500** [comment]
Hi Anne,

Thanks for fixing things, I managed to navigate the lab ok.  One thing to point out.  I am using my Cisco MacBook. When I open a terminal session it defaults me to root of the machine and I didn’t have the privileges to run the Python environment commands.  I changed to my own user directory and it was fine but, given this is a novice level training, it might be worth putting a note in to that effect.  The other part that wasn’t immediately obvious is that running the python code that was created from Postman, you need to run the command with the path to where the file was saved, or from the directory it was saved to.  Again, novice level (and I am a true novice) its not immediately obvious.  I did work it out though so I am definitely learning 😊

Regards

Mike
