### ISSUE TITLE
Ansible docs link broken in dne-dci-intro-nxos-06_ansible-nxapi/3.md 

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#271]
Repo: devnet-express-dci-nxos
Broken link found by the link checker: 
FILE: ./labs/dne-dci-intro-nxos-06_ansible-nxapi/3.md
[✖] http://docs.ansible.com/ansible/list_of_network_modules.html

**Comment by dethanga** [comment]
@annegentle and cc @klevenstein 
To fix the broken link, I found this link as matching, please check and let me know to proceed further. I will update the file accordingly. 
https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html 

Thanks - Devi

**Comment by annegentle** [comment]
Or, take a look at this list of "network platforms" -- what do you think? https://docs.ansible.com/ansible/latest/network/user_guide/platform_index.html 

@bigevilbeard Is this something you could take a look into?

**Comment by bigevilbeard** [comment]
Most of the links i found are considered out of date now, a like for like replacement i could not find. I think both could be a useful reference to users - HTH

**Comment by dethanga** [comment]
@annegentle and cc @bigevilbeard 
Hi Anne, Per directions from Stuart, I have added the network platform and resource module links in the respective file. Raised PR for your approval, kindly check.  
https://github.com/CiscoDevNet/devnet-express-dci-nxos/pull/8
Thanks - Devi

**Comment by dethanga** [comment]
@annegentle and cc @bigevilbeard 
Hi Anne, Thanks for approving the PR. 
The Lab is released and published to production.
https://developer.cisco.com/learning/lab/dne-dci-intro-nxos-06_ansible-nxapi/step/3
Hence, I am closing this issue. 

Thanks  - Devi
