### ISSUE TITLE
Deploying an Application on Catalyst 9K

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#277]
In the learning lab https://developer.cisco.com/learning/modules/app-hosting-cat9k/app-hosting-deploy/step/2 the step here is not supported. The current IOS XE version will support AppGig interface only in Trunk mode, not Vlan mode. Also missing syntax around the last line `run-opts` and why the number (option) is required.

```
app-hosting appid iperf
 app-vnic AppGigEthernet vlan-access
  vlan 4000 guest-interface 0
   guest-ipaddress 10.10.20.101 netmask 255.255.255.0
 app-default-gateway 10.10.20.254 guest-interface 0
 app-resource docker
  run-opts "--restart=unless-stopped -p 5201:5201/tcp -p 5201:5201/udp
```

The correct (new) way should be

```
app-hosting appid iperf
 app-vnic AppGigEthernet trunk
  vlan 4000 guest-interface 0
   guest-ipaddress 10.10.20.101 netmask 255.255.255.0
 app-default-gateway 10.10.20.254 guest-interface 0
 app-resource docker
  run-opts 1  "--restart=unless-stopped -p 5201:5201/tcp -p 5201:5201/udp
```

**Comment by dethanga** [comment]
@bigevilbeard and cc @klevenstein 
Hi Stuart, Thanks for your notes!
I have updated the repo with updated syntax. Released and published to production.
https://developer.cisco.com/learning/modules/app-hosting-cat9k/app-hosting-deploy/step/2
Kindly check and approve! Then I will close this issue. 
Thanks - Devi

**Comment by klevenstein** [comment]
Looks good, closing.
