### ISSUE TITLE
Unable to install dnac_config module error

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#278]
On this learning lab, https://developer.cisco.com/learning/tracks/dnacenter-programmability/dnac-rest-apis/dnac-101-auth/step/2 the import set up is not inline with the python code.

https://github.com/CiscoDevNet/dnac-apis-with-python-sample-codes/blob/master/basic-labs/dnac_config.py

Issue is seen

```
>>> from dnac_config import DNAC
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dnac_config'
```

Incorrect

```
import requests
from requests.auth import HTTPBasicAuth
from dnac_config import DNAC, DNAC_PORT, DNAC_USER, DNAC_PASSWORD
```

This should be in the learning lab

```
import requests
from requests.auth import HTTPBasicAuth
from dnac_config import DNAC_IP, USERNAME, PASSWORD

requests.packages.urllib3.disable_warnings()

def get_auth_token():
    url = 'https://sandboxdnac.cisco.com/dna/system/api/v1/auth/token'
    resp = requests.post(url, auth=HTTPBasicAuth(USERNAME, PASSWORD), verify=False)
    token = resp.json()['Token']
    print("Token Retrieved: {}".format(token))
    return token

if __name__ == "__main__":
 get_auth_token()
```

**Comment by dethanga** [comment]
@bigevilbeard and cc @klevenstein 
Thanks for approving the PR. Published the changes to staging and verified.
Pushed to Production! https://developer.cisco.com/learning/lab/dnac-101-auth/step/2
Thanks - Devi
