### ISSUE TITLE
Broken links in Cisco Webex Teams 101 module

### ISSUE THREAD

**Issue by klevenstein** [CiscoDevNet/learning-labs-issues#279]
Reported [https://learningnetwork.cisco.com/s/question/0D53i00000msfXw/cisco-webex-teams-api-101-module-broken-link?t=1604606525626](here).

> The Cisco Webex Teams API 101 Module located at:
> https://developer.cisco.com/learning/modules/business-messaging/collab-spark-apps/step/1
>
> Step 1: About Webex Teams Extensibility has the line:
> To automate tasks, custom applications use the Webex Teams REST API.
> The "Webex Teams REST API" takes you to the following link which is broken:
> https://developer.webex.com/quick-reference.html

**Comment by vvaliapa** [comment]
Corrected the broken links and published the Lab. Here is the updated Lab: https://developer.cisco.com/learning/lab/collab-spark-apps/step/1.
