### ISSUE TITLE
SD-WAN Getting Started

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#280]
The following needs to be updated please, from learning lab https://developer.cisco.com/learning/tracks/sd-wan_programmability/sd-wan/intro-sd-wan-rest-api/step/1

Prerequisites section

- Please update URL to https://devnetsandbox.cisco.com/RM/Diagram/Index/c9679e49-6751-4f43-9bb4-9d7ee162b069?diagramType=Topology
Update username/password to admin/C1sco12345

Thanks!

**Comment by vvaliapa** [comment]
Updated the sandbox link https://devnetsandbox.cisco.com/RM/Diagram/Index/c9679e49-6751-4f43-9bb4-9d7ee162b069?diagramType=Topology in the Introduction topic and Using the Cisco SD-WAN DevNet Sandbox topic.
Here is the updated Lab: https://developer.cisco.com/learning/lab/intro-sd-wan-rest-api/step/1
