### ISSUE TITLE
K8s cluster not accessible from 'Cisco DevNet Containers v1'

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#282]
Issue is seen/reported at https://community.cisco.com/t5/devnet-sandbox/k8s-cluster-not-accessible-from-cisco-devnet-containers-v1/m-p/4188975

I'm using the dCloud environment 'Cisco DevNet Containers v1' for the module at https://developer.cisco.com/learning/tracks/containers/containers-intro-1/containers-deploy-to-k8s/step/1.  This choice was based on the guidance at https://developer.cisco.com/learning/tracks/containers/containers-lab/containers-verify/step/2. 

That guidance stated:
The lab pod is available at https://dcloud.cisco.com.

Navigate to the Catalog tab.
Select DevNet from the Content Producers menu on the left.
Select DevNet Containers Pod from the list.
Follow the setup instructions.

Note: there was no 'DevNet Containers Pod' in the dCloud Catalog under the 'DevNet' Content Producer type like the document at https://developer.cisco.com/learning/tracks/containers/containers-lab/containers-verify/step/2 indicated there should be, not sure if this is relevant.  So I went with the closest environment of the 4 listed in dCloud, which was 'Cisco DevNet Containers v1'.

When I go to run any 'kubectl' commands in the module, I get an error:
"The connection to the server 198.18.1.157:6443 was refused - did you specify the right host or port?"

It seems my developer environment cannot access the K8s cluster.  In the Lab Guide for this environment accessible via https://dcloud2-rtp.cisco.com/content/demo/633348?returnPathTitleKey=content-view, there is no mention of the host 198.18.1.157.  I can ping 198.18.1.157 however, though I don't know the credentials to SSH into it.
I tried updating the kubeconfig file as described in https://developer.cisco.com/learning/tracks/containers/containers-intro-1/containers-deploy-to-k8s/step/1 even though this should not have been necessary since I was using the dCloud lab.  It didn't help.  I see the reference to 198.18.1.157 in the kubeconfig file.

 Please advise if I am using the wrong environment or something -- I had completed the earlier tasks in the same track at https://developer.cisco.com/learning/tracks/containers without issue.  Thanks.

**Comment by annegentle** [comment]
Ticket TKT-92466 logged in the dcloud ticket system.

**Comment by annegentle** [comment]
Hi, investigating this further, on dcloud, when connected to the VPN you can reach IOx and CCP from a local development environment, but connecting on dcloud from the RDP session to the CentOS box is not working. So we have made this track unavailable for now since you can't run it as written with the given infrastructure.

**Comment by annegentle** [comment]
Infrastructure issues are resolved; closing Issue.
