### ISSUE TITLE
ACI + Terraform lab

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#284]
The Intro to ACI + Terraform lab, looks like we are missing the link to the relevant GitHub repo.
On the 2nd page, it mentions the main.tf to define the provider and explicitly calls out the repo that was cloned at the beginning, https://developer.cisco.com/learning/lab/intro-to-aci-terraform-start/step/2
However, there is no mention of where to get it from. Doing some digging looks to be this repo from Lionel
https://github.com/lhercot/aci_terraform_learning_labs_code_samples

**Comment by qsnyder** [comment]
@bigevilbeard -- there may be some cleanup required here.  Wanted to get the labs published prior to a launch date.  We can work to get that **learning_labs_code_samples** repo transferred over to the **CiscoDevNet** organization and then clean up the lab instructions.

**Comment by annegentle** [comment]
Hey @qsnyder -- there's a blank repo at the ready at https://github.com/ciscodevnet/aci_terraform_learning_labs_code_samples -- so yep, all that's left to do is transfer the repo and then update the LL.

**Comment by qsnyder** [comment]
Pulled from Lionel's repo -- and pushed main to the empty repo.  All pointers in the learning labs look to have already been written to the CiscoDevNet repo -- so won't need to update anything else.  Will close, unless someone has objections

**Comment by annegentle** [comment]
Hi @qsnyder - the byod.html file still refers to the lhercot https for the git clone command - can you please fix? Thanks! 
<img width="878" alt="Screen Shot 2021-01-06 at 2 25 22 PM" src="https://user-images.githubusercontent.com/501981/103816796-2933ab80-502b-11eb-9f80-ae462bca46d8.png">

**Comment by qsnyder** [comment]
Changes made to `main`.  Just need to republish.

**Comment by qsnyder** [comment]
Just published a new version within GH.

**Comment by qsnyder** [comment]
Confirmed in staging and pushed update to prod.  Looks good on my end.
