### ISSUE TITLE
ACI + Terraform Lab + Consistency

### ISSUE THREAD

**Issue by mipetrin** [CiscoDevNet/learning-labs-issues#285]
The intro module uses the variable as "terraform_tenant" in the main.tf file where as the remaining labs (network policies, application policies, contract policies) all utilize "terraform-tenant". Would be good to keep it all consistent, with a dash instead of underscore, as the labs build upon each other. Update the intro_module main.tf to use "terraform-tenant".

**Comment by qsnyder** [comment]
@mipetrin -- Do you have a specific lab/task number where this discrepancy resides?  I just flipped through the code and the lab guide for both the intro and the network policy sections -- and I couldn't see it (but I've been accused of not having great abilities to find things :smile: )

**Comment by mipetrin** [comment]
Hey @qsnyder , nope, you are right. Not sure when it changed, maybe during the transfer from Lionel's repo to DevNet as part of #284, but I checked all the main.tf files in the 4 folders and all are now consistently using the tenant name as "terraform_tenant".

https://github.com/CiscoDevNet/aci_terraform_learning_labs_code_samples/blob/main/intro_module/main.tf
https://github.com/CiscoDevNet/aci_terraform_learning_labs_code_samples/blob/main/network_policies/main.tf
https://github.com/CiscoDevNet/aci_terraform_learning_labs_code_samples/blob/main/contract_policies/main.tf
https://github.com/CiscoDevNet/aci_terraform_learning_labs_code_samples/blob/main/application_policies/main.tf

**Comment by qsnyder** [comment]
@mipetrin -- I was the one who moved the repo over -- and I just changed the remotes -- so it probably didn't happen then ;-).  I didn't squash the commit history -- so if you're really curious -- I'll bet its in there.  Otherwise -- I'll just close the issue.  Glad my eyes actually worked this time.
