### ISSUE TITLE
Cisco Webex For Developers: Problem with /messages POST HTTP Method

### ISSUE THREAD

**Issue by klevenstein** [CiscoDevNet/learning-labs-issues#289]
Issue spotted on [Learning Network](https://learningnetwork.cisco.com/s/question/0D53i00000mthNVCAY/cisco-webex-for-developers-problem-with-messages-post-http-method):

> As part of the DevNet Associate Learning Map track, there is a lab with the Cisco Webex Teams API:
> https://developer.cisco.com/learning/devnet-express/devnet-express-meraki/rest-api-fundamentals/what-are-rest-apis/step/4
>  
> So the main lab steps are:
>  
> 1. Sign up for a Cisco Webex for Developers Account (successful)
> 2. Login with the Webex Account and retrieve the (temporary) authentication token for authentication when using the APIs (successful)
> 3. Using the online service provided on the same page, test the /people API to get your id (successful)
> 4. Using the /messages api and your id in step 3, send a message to yourself using curl (failed)
>  
> So the first problem with step 4 is that they tell you to get the id from step 3 and use it but the code (curl command) given for step 4 does not use the id from step 3. The code that was given for the lab is:
>  
> Code 1:
> `$ curl https://webexapis.com/v1/messages -X POST -H "Authorization:Bearer MDg...zRh4" --data "toPersonEmail=someone@cisco.com" --data "text=Hi%20from%20DevNet"`
>  
> Note that the Code 1 above requires the user's email address for the Webex account instead of the id retrieved from step 3.
> What should have been given instead is:
>  
> Code 2:
> `$ curl https://webexapis.com/v1/messages -X POST -H "Authorization:Bearer MDg...zRh4" --data "toPersonId=enteryouridfromstep3" --data "text=Hi%20from%20DevNet"`
>  
> However, whether I used Code 1 above with my email address or Code 2 with my id I get the following error:
```
{
  "message": "Failed to create room.",
  "trackingId": "WEBEX-DEV-PORTAL_d7be20df-371b-41b5-8359-f3f6e893734a_17"
 }
```  
> Can someone help me with this command/API?
> If I am sending a message directly to someone, why is it trying to create a room?
>  
> Also if you are telling the person to use Code 2 then Code 1 in the lab should be corrected with Code 2 instead.
> 
>  
> Just to make sure that curl is working with another API, I tried step 3 again but using curl instead of the API Web page:
>  
> Code 3:
> `curl -H "Authorization:Bearer iputmyauthenticationtokenhere" https://webexapis.com/v1/people/me` 
>  
> Output:
```
 {
  "id": "Y2lzY9zcGFazovL3VfzL1BFT1BgMRS9jZjQ1OGRmYi0zZmYyLTQyNjUtODRiZC0yYWI5OTdmNzI3MDI",
  "emails": [
   "myemail@mydomain.com"
  ],\ "phoneNumbers": [],
  "displayName": "Andre Thompson",
  "nickName": "Andre",
  "firstName": "Andre",
  "lastName": "Thompson",
  "orgId": "Y2lzY29zcGFyazovh3VzL09SR0FgSVpBVElPTi9jb25zdW1lcg",
  "created": "2020-05-27T15:34:33.162Z",
  "status": "unknown",
  "type": "person"
 }
```  
> I would like to humbly suggest that Code 3 be step 3.5 so that the user has something easy to perform first using the curl command.
>  
> Step 4 will build upon step 3 by providing more arguments in the curl command including the POST HTTP Method.

From Karlo Bobiles:
> Thanks for the update. Although the steps indicate to enter your email address for the toPersonId, you should actually enter someone else's email other than yours.

**Comment by annegentle** [comment]
I revised - the instructions were mixed between the v1/people/me call and a POST command to make a message. So I've revised so the command the user performs is a GET rather than a POST so they don't have to gather as much information.
