### ISSUE TITLE
Missing pyATS install step? 

### ISSUE THREAD

**Issue by labeveryday** [CiscoDevNet/learning-labs-issues#290]
On step 4 of the Learning Lab there is a step that has you to do a `pip list | grep pyats` but no where in the lab do you install pyats. I checked in the `introduction to pyats` lab and this does not have you install pyats either. 

Here's the link to the Learning Lab: [Intro to Genie](https://developer.cisco.com/learning/lab/intro-to-genie/step/4)

**Comment by vvaliapa** [comment]
Updated the pyATS install steps in https://developer.cisco.com/learning/lab/intro-to-genie/step/4.
