### ISSUE TITLE
Update app-dynamics-docker/ lab with edits to two Dockerfiles

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#292]
there's a bug in the appd lab at

 https://developer.cisco.com/learning/tracks/cisco-app-first-security/appdynamics-perf-mon/app-dynamics-docker/step/2

looks like there was a redirect introduced from the site that serves gradle … need to edit two files from https://github.com/Appdynamics/AD-Capital-Docker.git
1. ADCapital-Project/Dockerfile
2. ADCapital-Load/Dockerfile
RUN curl -O http://downloads.gradle.org/distributions/gradle-2.1-bin.zip —>> RUN curl -LO http://downloads.gradle.org/distributions/gradle-2.1-bin.zip

**Comment by klevenstein** [comment]
@annegentle: Update: I've tried to get in touch with the maintainers of the AD-Capital-Docker repo, but none of them have gotten back to me. Since we can't really do anything with the dockerfiles in that repo without access, I'm not sure what else we can do.

**Comment by annegentle** [comment]
You can assign it to me, I think I know how to fix the Dockerfiles.

**Comment by annegentle** [comment]
Oh, closing this Issue - Randy Birdsall fixed it in March.
