### ISSUE TITLE
Homebrew syntax has changed

### ISSUE THREAD

**Issue by Lemandros** [CiscoDevNet/learning-labs-issues#293]
For the macOS dev setup, some commands involving Homebrew are given of the form "brew cask install [name]". This should now be changed to "brew install --cask [name]" 
See e.g. https://stackoverflow.com/questions/30413621/homebrew-cask-option-not-recognized

**Comment by annegentle** [comment]
I fixed it in this page: https://developer.cisco.com/learning/modules/dev-setup/dev-mac/step/7 I mention it in this page also: https://developer.cisco.com/learning/modules/dev-setup/dev-mac/step/2

Can you let me know if there are other places that you saw it?

**Comment by annegentle** [comment]
Fixed where we found it; closing.
