### ISSUE TITLE
Broken links in SecureX Serverless Relay module

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#294]
User reports some broken links on https://developer.cisco.com/learning/tracks/SecureX/securex-serverless-relay-modules/SecureX-2-CTIM/step/3

Models
CITM contains the following data models. Click on each link to read more about the models.
Actor
Attack Pattern
Campaign

Another incorrect link on https://developer.cisco.com/learning/tracks/SecureX/securex-serverless-relay-modules/SecureX-5-Relay_Module_Integration/step/5 - check the Webex link.

**Comment by dethanga** [comment]
@klevenstein and cc @annegentle 

Thanks for the approval, Karin. I have released and published the changes to production. 

Regards - Devi
