### ISSUE TITLE
Check the JSON for "next lab" in the meraki-12-mission-3 Lab

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#296]
When clicking through the entire DevNet Express for Meraki, I got to https://developer.cisco.com/learning/devnet-express/devnet-express-meraki/meraki-dashboard-api/meraki-12-mission-3/step/4 and then clicked Next. 

The Next button does not work and a next Lab title does not appear, so I think probably the JSON file doesn't have the correct related IDs.

**Comment by dethanga** [comment]
@annegentle and cc @klevenstein - Hi Anne, I have checked your notes. 
This Lab is the last task/mission for the user to complete the Meraki DevNet Express track, which is the "Meraki External Captive Portal (EXCap) mission 3". 
Once I clicked the arrow provided on the right-side - end of the page. I got the below screen.
![image](https://user-images.githubusercontent.com/41729073/118638360-650a2900-b7f4-11eb-8982-574a9208253f.png)
Here my understanding is: the page automatically directs the user to take Lab which in progress in the same module/track.
Please let me know if anything I need to check on this. 

Thanks - Devi

**Comment by annegentle** [comment]
Working as expected - must have been a fluke that day! Closing.
