### ISSUE TITLE
broken link ansible lab

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/learning-labs-issues#297]
https://developer.cisco.com/learning/modules/sdx-ansible-intro/ansible-02_ansible-intro/step/2

at the bottom of the page the link goes to a 404 not found.

**Comment by annegentle** [comment]
Change the link to https://docs.ansible.com/ansible/latest/reference_appendices/config.html in https://github.com/CiscoDevNet/sandbox-dci-ansible/blob/master/labs/ansible-02_ansible-intro/2.md

**Comment by dethanga** [comment]
@annegentle and cc @klevenstein  - Thanks for sharing the fix. I have updated the link for "configuration options".
The updated repo is released and published: https://developer.cisco.com/learning/modules/sdx-ansible-intro/ansible-02_ansible-intro/step/2

Thanks - Devi
