### ISSUE TITLE
Broken link to Cisco UCS PowerTool Suite

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#298]
The link for Cisco UCS PowerTool Suite is broken does not open the correct page 

https://developer.cisco.com/learning/lab/ucsm-powertool-101/step/1

This should be this link https://software.cisco.com/download/home/286305108/type/284574017/release/2.5.1

Thanks!

**Comment by dethanga** [comment]
@bigevilbeard and cc @klevenstein 
Hello Stuart, thanks for helping to fix the broken link issues.
I have released the Lab and pushed it to production: https://developer.cisco.com/learning/lab/ucsm-powertool-101/step/1 Thanks - Devi
