### ISSUE TITLE
SD-WAN Day One automation with Ansible | Update Step 2

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#299]
Please update the section 

``
Note: The previous output is generated by the tree command. If you want to install it on the DevBox, you can do so with sudo yum install tree and, then see the directory structure of the inventory directory with tree `./inventory.``

To 

``
Note: The previous output is generated by the tree command-line utility which is pre-installed. If you want to view this, you can do so with `tree ./inventory` and the view directory structure of the inventory directory in this format.
``

https://developer.cisco.com/learning/modules/sd-wan-ansible-pipeline/sdwan-automation-dayone-config/step/2

**Comment by dethanga** [comment]
@bigevilbeard  and cc @klevenstein 

Thanks for sharing the updated "Note". The respective file is updated and published to production.
https://developer.cisco.com/learning/lab/sdwan-automation-dayone-config/step/2

Thanks - Devi
