### ISSUE TITLE
Set scope public as a list data type in intro-to-aci-terraform-policies

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#300]
Reported by Jungnam Kim in the DevNet 500 space:

In the Lab at devloper.cisco.com, you need to fix the wrong part.
URL: https://developer.cisco.com/learning/modules/terraform-aci-intro/intro-to-aci-terraform-policies/step/2
Before : scope = "public"
After : scope = ["public"]
Because the datatype of the scope of Terraform's subnet is a list.

**Comment by dethanga** [comment]
@annegentle - Thanks for approving and merging the changes. 
I have released and published the Lab to production: https://developer.cisco.com/learning/lab/intro-to-aci-terraform-policies/step/2
