### ISSUE TITLE
When DevNet Express students run "pip install" commands, pip always "reminds" you to update

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#302]
Add a note to students that it's okay to ignore the Warning message that Pip gives you that you need to update Pip. Pip sometimes updates weekly so this message happens often, and it's good for students to know this is part of a "normal" Python developer environment to see this message every once in a while. You can either ignore it and upgrade pip later, or upgrade pip as instructed. 

Go through one of the DNE dcloud devboxes to copy/paste the exact message to use for the note.

**Comment by ianhawki** [comment]
When you are verifying the environment in a DNE lab. One of the commands you run is "pip install -r requirements.txt", some times we see an error at the end of the script that indicates PIP needs upgrading. (see graphic)

![grab533](https://user-images.githubusercontent.com/4444392/113926654-c91df280-982f-11eb-84fd-793ba81b0766.jpg)

Can we add in the lab guides to be aware of this and add the line of code needed to fix it as an instruction. 

"pip install --upgrade pip"

and then rerun the "pip install -r requirements.txt" command to complete error free.

**Comment by annegentle** [comment]
The image has been changed but the note still applies, so closing Issue.
