### ISSUE TITLE
Insecure remote desktop session prevents clipboard sharing

### ISSUE THREAD

**Issue by wattsjs** [CiscoDevNet/learning-labs-issues#303]
The remote desktop portal (Guacamole) is not configured for SSL/HTTPS and therefore Chrome disables clipboard sharing between the users' machine and the remote desktop.

When launching from dCloud the following URL:
**https**://dcloud2-sng.cisco.com/sessions/
is redirected to:
**http**://dcloud-sng-web-4.cisco.com/dCloudConnect

**Comment by annegentle** [comment]
I don't have a good place to put a fix for this in the Learning Lab itself. My understanding is that the proctors are all aware of the limitation. Closing issue for now as there is not a Learning Lab fix we can do.

**Comment by annegentle** [comment]
Please reopen if you have a specific location you are thinking of for placement.
