### ISSUE TITLE
SD-WAN Learning Lab wrong API docs link

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#309]
Step 4 of the first lab. https://developer.cisco.com/learning/tracks/sd-wan_programmability/sd-wan/intro-sd-wan-rest-api/step/4

It is the link to the vManage REST API docs, if you click it, it goes to the legacy viptela page, which redirects you right back to the DevNet page for the v,manage docs. The correct link to go here: https://developer.cisco.com/docs/sdwan/#!introduction

Also would be good to update the image too please. Ta

**Comment by dethanga** [comment]
Hi @bigevilbeard - Thanks for approving the changes. I have merged the changes to Master and published the Lab.
https://developer.cisco.com/learning/lab/intro-sd-wan-rest-api/step/4

cc @klevenstein 

Regards,
Devi
