### ISSUE TITLE
CI/CD Intro

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#311]
Please can you check the learning lab cicd-intro? Reported in the CLN IPs don't match the Sandbox lab, there is an extra 'kubernetes_token' attribute in the drone YAML file, set to a placeholder value, that isn't referenced at all in the Lab.

https://developer.cisco.com/learning/lab/cicd-intro

**Comment by annegentle** [comment]
Deactivated LL.
