### ISSUE TITLE
Broken link to GitHub solution code

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#315]
FILE: ./labs/dnav3-dnac-nbapi-mission/summary.md
[✖] https://github.com/CiscoDevNet/dne-dna-code/tree/solutions/intro-dnac/dnac-nbapi-mission

The link should go to https://github.com/CiscoDevNet/dne-dna-code/tree/solutions/intro-dnac

**Comment by dethanga** [comment]
@annegentle, thanks for approving the changes.
I have released and published the Lab. 
Thanks - Devi
