### ISSUE TITLE
Broken links to developer.webex.com in labs/collab-webex-intl/1.md

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#317]
There are a couple of broken links to developer.webex.com pages that should be fairly easy to fix:

FILE: ./labs/collab-webex-intl/1.md
[✖] https://developer.webex.com/authentication.html
[✖] https://developer.webex.com/endpoint-people-me-get.html

**Comment by vvaliapa** [comment]
Fixed and published the Lab: https://developer.cisco.com/learning/lab/collab-webex-intl/step/1
