### ISSUE TITLE
Broken link to developer.webex.com in collab-webex-webhook/4.md

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#318]
Replace with https://developer.webex.com/docs/api/guides/webhooks

FILE: ./labs/collab-webex-webhook/4.md
[✖] https://developer.webex.com/webhooks-explained.html

**Comment by vvaliapa** [comment]
Fixed and published the Lab: https://developer.cisco.com/learning/lab/collab-webex-webhook/step/4
