### ISSUE TITLE
Update User/Pass Understanding ACI LL

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#319]
Please update Learning Lab https://developer.cisco.com/learning/modules/intro-to-aci/sbx-intro-aci-01_understanding-aci/step/6 with new/correct sandbox username/password 

```
The server can be connected using login credentials admin and password : !v3G@!4@Y
```

https://devnetsandbox.cisco.com/RM/Diagram/Index/18a514e8-21d4-4c29-96b2-e3c16b1ee62e?diagramType=Topology

**Comment by vvaliapa** [comment]
Updated the correct password.
