### ISSUE TITLE
Substitute sslip.io for xip.io in containers-intro-service-mesh

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#320]
In the file at /4-Istio_lab2_Instal_myhero.md substitute sslip.io for xip.io. You'll also want to do the substitution in the YAML example file in the repo.

**Comment by dethanga** [comment]
Hi @annegentle,

https://github.com/CiscoDevNet/containers-dne-labs/pull/132 is reviewed and approved. The changes are merged to Master. 
We can complete this task. 
Note: Changes are done in script files, hence publishing to LL staging/production is not required. 

Thanks - Devi
