### ISSUE TITLE
Learning lab: Introduction to guestshell failed to install nano, git

### ISSUE THREAD

**Issue by urozman** [CiscoDevNet/learning-labs-issues#323]
https://developer.cisco.com/learning/modules/net_app_hosting/intro-guestshell/step/1

It this lab there is a step to install nano and vim in guestshell. (sandbox IOS XE Recommended code, always on)

STEP AND EXPECTED OUTPUT:
**Now let's install `git` and `nano` using `yum`:**

```
```
[guestshell@guestshell ~]$ sudo yum install -y git nano
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.atlanticmetro.net
 * extras: mirrors.greenmountainaccess.net
 * updates: ftp.osuosl.org
...
<output omitted>
...
```
Complete!
``` 

ACTUAL OUTPUT:

```
csr1000v-1#guestshell
[guestshell@guestshell ~]$ sudo yum install nano, git -y
CentOS-8 - AppStream                                                                                                                                                                           0.0  B/s |   0  B     00:10    
Failed to download metadata for repo 'AppStream'
Error: Failed to download metadata for repo 'AppStream'
[guestshell@guestshell ~]$
```

**Comment by urozman** [comment]
This step is describer here: 

https://devnetapps.cisco.com/learningcenter/labs/dnav3-intro-guestshell/step2033a20using20additional20utilities20inside20the20guest20shell

**Comment by annegentle** [comment]
Hi @urozman - I'm not seeing "Now let's install git and nano using yum:" on that link... did you click "How to Setup Your Own Computer" and then choose "Setting up your Linux (CentOS) workstation as a development environment" to get to the "Now let's install git and nano using yum:"? Or am I seeing this incorrectly? Totally possible : )

**Comment by urozman** [comment]
Hi @annegentle . Yes you're right. Those steps are new for the new platform. I already post the link in the comment: 

https://devnetapps.cisco.com/learningcenter/labs/dnav3-intro-guestshell/step2033a20using20additional20utilities20inside20the20guest20shell

**Comment by annegentle** [comment]
Closing, thanks for logging as it shows the confusion and we found a related problem!
