### ISSUE TITLE
Ansible solution failed in nxos-intro-mission-02_ansible-mission"

### ISSUE THREAD

**Issue by urozman** [CiscoDevNet/learning-labs-issues#324]
Solution folder is not complete in the git repository: DevNetSandbox/sbx_nxos/LM-5601 open-nxos/nxos-intro-mission-02_ansible-mission

Clone https://github.com/DevNetSandbox/sbx_nxos and navigate to directory: LM-5601 open-nxos/nxos-intro-mission-02_ansible-mission.
Try to run the solution file from the directory solutions: ansible-playbook -u root site.yml

There are folders that are missing, so the solution can not be run without student adding those files to the solution folder.

**Comment by annegentle** [comment]
I looked into this, and I'm going to close this Issue for now since the LL have been deactivated for a while now. The student will need to figure out that they need to make those folders once we reactivate that LL.
