### ISSUE TITLE
Find an alternative to https://github.com/kiskander/DNAC-101-Code repo for dnac-101-network_device LL

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#328]
Kareem thought the code example was identical to https://github.com/CiscoDevNet/DNAC-Top5/blob/master/01_network_device.py, but the code examples are different. Try to track down a "CiscoDevNet" code repo with the example.

**Comment by annegentle** [comment]
I'll ask @kiskander  to transfer the repo to CiscoDevNet.

**Comment by klevenstein** [comment]
Could the code be here? https://github.com/CiscoDevNet/dne-dna-code

This was where we moved the code for the DNAC DNE, and it might be the same.

**Comment by klevenstein** [comment]
Copied it over; closing.
https://github.com/CiscoDevNet/dne-dna-code/tree/master/intro-dnac/02_Network_Devices
