### ISSUE TITLE
dcloud Link update in developer.cisco.com/learning/tracks/stealthwatch/swc/Intro-SWC-APIs/step/3

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#329]
The current dcloud link in developer.cisco.com/learning/tracks/stealthwatch/swc/Intro-SWC-APIs/step/3 is incorrect. Use this instead:

https://dcloud2-rtp.cisco.com/content/instantdemo/cisco-stealthwatch-cloud-v2-instant-demo?returnPathTitleKey=content-view

I believe this source is in veeratcisco or some such, so assigning to @klevenstein

**Comment by klevenstein** [comment]
Done: https://developer.cisco.com/learning/lab/Intro-SWC-APIs/step/3
