### ISSUE TITLE
NXOS Sandbox [Getting Hands On with Ansible] no longer available

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#330]
There is a reference to an NXOS Sandbox that is no longer available, is there a replacement for this SandBox and also Ansible Lab, as Open NX-OS with Nexus 9Kv is decommissioned.

https://developer.cisco.com/learning/modules/sdx-ansible-intro/ansible-03_ansible-hands-on/step/1

This LL should be updated to use Cisco Modeling Lab sandbox https://devnetsandbox.cisco.com/RM/Diagram/Index/685f774a-a5d6-4df5-a324-3774217d0e6b?diagramType=Topology

**Comment by annegentle** [comment]
LL no longer refers to the NXOS Sandbox; closing.
