### ISSUE TITLE
Guest accounts are no longer possible on dCloud

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#332]
Guest accounts are no longer possible on dCloud. This LL Track https://developer.cisco.com/learning/tracks/containers, first module "Containers: Set up your lab environment" uses a dCloud Pod. I think they removed guest access (i can schedule this ok with Cisco ID)

![06_00_02](https://user-images.githubusercontent.com/25031708/148693188-42b4449e-10fe-421b-b21b-ec65b801b55c.jpg)

https://developer.cisco.com/learning/tracks/containers/containers-lab/containers-verify/step/
![05_59_51](https://user-images.githubusercontent.com/25031708/148693190-ce910737-f3cd-4046-b73f-2cd75be88021.jpg)
2

It is available to all users with a valid Cisco.com account only. We could ask user to create an account which might solve 70% of user cases, instruction on how to do this are here — > https://dcloud-cms.cisco.com/faqs/customer-access-to-dcloud

**Comment by akashchakraborty** [comment]
Is there any alternative? And registering as a customer is the only other option that will allow guests to create an account, will that be a chargeable issue for students?

**Comment by bigevilbeard** [comment]
@akashchakraborty our content team are working with the dCloud team and engineer and alternative registration and lab use.

**Comment by klevenstein** [comment]
Added access instructions and a link to the FAQ.
