### ISSUE TITLE
Parsing XML LL Error

### ISSUE THREAD

**Issue by bigevilbeard** [CiscoDevNet/learning-labs-issues#333]
https://developer.cisco.com/learning/labs/parsing-xml/step/1

Looking at the Learning Lab in the provided a link for, i see the username password in the code 

```
encoded_body = json.dumps({
            "aaaUser": {
                "attributes": {
                    "name": "admin",
                    "pwd": "ciscopsdt"
                 }
            }
})
```
Is not correct when you compare this to the sandbox instruction [HERE](https://devnetsandbox.cisco.com/RM/Diagram/Index/18a514e8-21d4-4c29-96b2-e3c16b1ee62e?diagramType=Topology).

Please update the code with the this username/password

```
encoded_body = json.dumps({
            "aaaUser": {
                "attributes": {
                    "name": "admin",
                    "pwd": " !v3G@!4@Y"
                 }
            }
})
```

**Comment by klevenstein** [comment]
Fixed and published
