### ISSUE TITLE
Need venv instead of virtualenv in latest Ubuntu version for dev-ubuntu LL

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#336]
https://developer.cisco.com/learning/lab/dev-ubuntu/step/5 tells the user to install `python3-virtualenv`. Instead the user should install `python3-venv`.
Reported by end user on latest Ubuntu version:

When I ran the command I got this error.
 
 
 
devnet@ubuntu:~$ python3.8 -m venv py3-venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.
 
    apt install python3.8-venv
 
You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.
 
Failing command: ['/home/devnet/py3-venv/bin/python3.8', '-Im', 'ensurepip', '--upgrade', '--default-pip']
 
 
This was the fix
sudo apt install python3.8-venv

**Comment by klevenstein** [comment]
Looks like the fix is made and published - user is now instructed to use ` sudo apt install python3.8-venv`. Closing.
