### ISSUE TITLE
Broken link to AppD docs in fnd-01-appd-apm-java/step/6

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#337]
There's a 404 coming up in a link to docs.appdynamics.com/display/latest/Dynamic+Baselines in fnd-01-appd-apm-java/step/6. Hopefully, there's a fairly straightforward way to see what's going on there.

**Comment by vvaliapa** [comment]
Hi Anne, 
I have fixed the broken link: Here is the PR: https://wwwin-github.cisco.com/DevNet-PubHub/llabsource-appd-learning-labs/pull/5

**Comment by vvaliapa** [comment]
Fixed and published the Lab: https://testing-developer.cisco.com/learningcenter/labs/fnd-01-appd-apm-java/monitor-and-troubleshoot-application-issues-part-1/
