### ISSUE TITLE
Python Primer 1 needs corrections

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/learning-labs-issues#42]
In a DevNet Tiger Team Spark room, Joel Jose noted the following errors. Steps 2 and 6 need to be corrected. The source content is in the following repo: 

> https://github.com/CiscoDevNet/intro-to-programming

<img width="874" alt="primer-1-errors" src="https://user-images.githubusercontent.com/8781860/36745734-091d8774-1c23-11e8-93fb-ec710dfc49e6.png">

**Comment by annegentle** [comment]
Fixed, closing.
