### ISSUE TITLE
Create slide deck to accompany parsing JSON lab

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/learning-labs-issues#43]
The lab on parsing JSON needs a slide deck to accompany it in classroom situations:

    Title: Using Python to Parse JSON
    Lab ID: intro-to-python-parsing-json
    Found in Module: https://learninglabs.cisco.com/modules/fundamentals
    Repo: https://github.com/CiscoDevNet/intro-to-programming

The above standalone version is not to be confused with the lab of the same title used by DevNet Express:
    Title: Using Python to Parse JSON
    Lab ID: python-parsing-json-1
    Found In Module LM-1221: https://learninglabs.cisco.com/modules/devnet-express-python-xml-programming-basics
    Repo: https://github.com/CiscoDevNet/intro-to-programming-devnet-express

**Comment by annegentle** [comment]
I think this can be closed with the latest decks we are using in DNE.
