### ISSUE TITLE
Remove old coding 101, 102, 103, etc labs and replace

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/learning-labs-issues#44]
The following labs are deprecated and should be removed:

  - Coding 101 - REST API Basics With APIC-EM
    - Coding 101 - REST API Basics (Japanese)
  - Coding 102: Calling REST APIs from Python
    - Coding 102: Calling REST APIs from Python (Japanese)

  - Coding 201 - Parsing XML
  - Coding 202 - Parsing JSON
  - Coding 203: Getting Input from a User Using Python
  - Coding 204: Reading data from a file using Python
  - Coding 205: Writing data to a file using Python
  - Coding 206: How to use the Python logging module
  - Coding 207: Python - Putting it all together

Where appropriate the labs should be replaced by the newer Python primers and the REST API intro labs.

**Comment by annegentle** [comment]
Closing.
