### ISSUE TITLE
Cisco Kinetic 101 - need info to activate account

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/learning-labs-issues#51]
No any information prior to step 1, don't think people can follow through.

https://learninglabs.cisco.com/labs/iot-data-connect-101/step/1/

Step 1: Activate your user account
**Open the "Confirmation instructions" email and click the activation link.**
Enter a password and click Change my password.
Open a web browser on your computer and enter the address provided by your company's Cisco Kinetic support representative.
Sign in using the email address and password for your account.

**Comment by annegentle** [comment]
This lab has been rewritten - closing. Thanks for reporting!
