### ISSUE TITLE
Rename Cisco Spark to Webex Teams - and all related renaming that ensues

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#62]
developer.ciscospark.com => developer.webex.com
Spark for Developers => Webex for Developers
#spark4dev => #webex4devs
developer token not accessible from avatar any more

Longer list available from Stève, Tessa, or Anne

**Comment by ObjectIsAdvantag** [comment]
This has been fixed when we worked on renaming (Autumn 2018)

> As **most Webex Teams users have many spaces**, we will use the filter parameter in our webhook request to restrict webhook notifications only for message events from the "Marketing Campaign" space. However, in order to filter by space, we first need to find out the unique identifier (id) of the target space.

https://developer.cisco.com/learning/lab/collab-sparkwebhook/step/2

**Comment by ObjectIsAdvantag** [comment]
We're good
Assigning to @klevenstein to close the issue

**Comment by klevenstein** [comment]
Closing; thanks Stève!
