### ISSUE TITLE
ACI Labs Webarya Flask Error

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/learning-labs-issues#64]
Fixes needed within DNE and nonDNE versions of lab: 

https://github.com/CiscoDevNet/sbx-intermediate-aci/blob/master/labs/sbx-intermediate-aci-00_webarya/2.md

https://github.com/CiscoDevNet/devnet-express-dci-intermediate-aci/blob/master/labs/dne-dci-intermediate-aci-00_webarya/2.md 

Reported from SE, haven't had a chance to verify but logging.  

From: Luca Palermo <luca.palermo@outcomex.com.au>
Date: Tuesday, 29 May 2018 at 2:04 pm

I am working on running the ACI Programmability track internally to the team.
 
While testing the Webarya, I discovered that one of the library imported in the script is deprecated and the installation fails:
 
`ImportError: flask.ext.bootstrap`

The work around I found is this:

1. comment flask.ext.bootstrap import Bootstrap in the webarya.py
1. use this instead flask_bootstrap import Bootstrap

Please look https://pypi.org/project/Flask-Bootstrap/ for more reference.

**Comment by klevenstein** [comment]
Looks like this issue has been fixed in the webarya.py file: https://github.com/datacenter/webarya/commit/2a94fccbcb0097d3162b619524ef93cd11a94d34

Closing for now; reopen if needed.
