### ISSUE TITLE
What and Why of Model Driven Programmability - How To Setup Your Own Computer links should open in a new tab

### ISSUE THREAD

**Issue by ascendingtom** [CiscoDevNet/learning-labs-issues#68]
in lab https://testing-developer.cisco.com/devnetlearninglabs/modules/intro-device-level-interfaces/why-mdp/step/1 

"How To Setup Your Own Computer" all the links should open in a new tab and not close the learning lab like all the other links in this lab

**Comment by annegentle** [comment]
Oh, yeah I see what you mean... that's a lotta `byod.html` files to work on but I'll see what we can do.

To triage, the fix is to edit the byod.html file in each lab. In the HTML set the `target="_blank"` on every `a href` link in the file.

**Comment by klevenstein** [comment]
@dethanga @vvaliapa This is a sort of ongoing thing; as you run across `byod.html` files, make sure the `target="_blank"` is set on the `a href` links.

**Comment by klevenstein** [comment]
To clarify my comment above: definitely don't try to do all of these at once. :) Basically, whenever you're already working on a lab, check the `byod.html` and fix.

**Comment by dethanga** [comment]
@klevenstein 

Thanks for your notes. We did basic research on how to fix the issue; will share our workflow in the status call. We will flow your instructions! 

Regards,
Devi

**Comment by klevenstein** [comment]
We've tested this out on staging and run into some suboptimal user experience—when the new window opens, the user is forced to log in again, even though they're already logged into developer.cisco.com.
