### ISSUE TITLE
All Cisco Live Session links need to change

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#69]
https://learninglabs.cisco.com/modules/intro-device-level-interfaces/why-mdp/step/7 has several broken links. The new pattern for Cisco Live Sessions is: 
https://ciscolive.cisco.com/on-demand-library/?search=BRKSDN-1119#/

**Comment by klevenstein** [comment]
Old pattern found in the following files:
https://github.com/CiscoDevNet/devnet-express-dna-japan - 7.md
https://github.com/CiscoDevNet/intro-standard-device-interfaces-learning-labs - 7.md
https://github.com/CiscoDevNet/coding-japan – summary.md
https://github.com/CiscoDevNet/dnav3-intro-mdp-labs – summary.md
https://github.com/CiscoDevNet/intro-mdp-labs – summary.md
https://github.com/CiscoDevNet/devnet-express – 7.md
https://github.com/CiscoDevNet/devnet-express – lab 5 - closing.md
https://github.com/CiscoDevNet/devnet-express-dna-japan – lab 1 - overview.md
https://github.com/CiscoDevNet/devnet-express – lab 1 - overview.md
https://github.com/CiscoDevNet/devnet-express-dna-japan – lab.md
https://github.com/CiscoDevNet/Real-Time-Client-RSSI-and-SNR-from-AP – README.md
https://github.com/CiscoDevNet/devnet-express – lab.md
https://github.com/CiscoDevNet/intro-mdp-labs – outline.md

**Comment by klevenstein** [comment]
https://github.com/CiscoDevNet/intro-mdp-labs/pull/7:

https://github.com/CiscoDevNet/devnet-express – 7.md
https://github.com/CiscoDevNet/devnet-express – lab.md
https://github.com/CiscoDevNet/devnet-express – lab 1 - overview.md
https://github.com/CiscoDevNet/devnet-express – lab 5 - closing.md

**Comment by klevenstein** [comment]
All instances of broken URLs should be addressed now.

**Comment by annegentle** [comment]
All these have merged and been published - closing.
