### ISSUE TITLE
Clarification or correction of information in Ansible hands on learning lab

### ISSUE THREAD

**Issue by KiranKumarKL** [CiscoDevNet/learning-labs-issues#74]
I am testing ansible learning lab. While setting up and verifying ansible infrastructure (https://learninglabs.cisco.com/modules/sdx-ansible-intro/ansible-03_ansible-hands-on/step/1) in dev sandbox, I found that the tested result of mine and the result shown in learning lab has the difference.

Verify the 2 main ansible CLI tools we will be using .

![inll](https://user-images.githubusercontent.com/46438105/50758776-290c4400-1289-11e9-9dcb-411dd7aacadf.PNG)

and results from my end

![frmyll](https://user-images.githubusercontent.com/46438105/50758840-56f18880-1289-11e9-93dc-47f487f29bde.PNG)

I could see the difference in both..like the location of the file..

Pls let me know if i am executing properly or not ?

Thanks

**Comment by annegentle** [comment]
Hi, I was able to make the change, thanks for reporting!
