### ISSUE TITLE
Ansible LL: Wrong host IP address need to be corrected 

### ISSUE THREAD

**Issue by KiranKumarKL** [CiscoDevNet/learning-labs-issues#75]
This is a minor correction:
While testing ansible learning lab, i found that the wrong IP address is given in the example. There are two instances of the same.
URL: https://learninglabs.cisco.com/modules/sdx-ansible-intro/ansible-03_ansible-hands-on/step/3

Instance 1:
![image](https://user-images.githubusercontent.com/46438105/50836926-71f2f400-1380-11e9-99ff-b645f2bfb40a.png)

instance 2:
![image](https://user-images.githubusercontent.com/46438105/50836976-8c2cd200-1380-11e9-937c-8fb626a44cca.png)

The Ip address should be 10.10.20.20

**Comment by annegentle** [comment]
Meant to do this sooner -thanks again for reporting.
