### ISSUE TITLE
Reviews/comments for Vagrant Up learning labs.

### ISSUE THREAD

**Issue by AnushaBR** [CiscoDevNet/learning-labs-issues#76]
[Vagrant_UP-learninglab_reviews.docx](https://github.com/CiscoDevNet/learning-labs-issues/files/2739614/Vagrant_UP-learninglab_reviews.docx)
Reviews/comments for Vagrant Up learning labs.

**Comment by Geevarghese** [comment]
Got a question in WebEx support room related to the second lab that  with 7.0.3.I6.1. Upon a second ‘vagrant up’, I get the “Welcome to the NX-OS VirtualBox.” message but ‘vagrant ssh’ fails.  Then was able to resolve the issue by downgrading VirtualBox to 5.2.26.  .   Client Name : Neal Secher@statestreet.com Date - 02-03- 2019(mm/dd/yyyy)
