### ISSUE TITLE
Issues for Getting Started With Meraki labs

### ISSUE THREAD

**Issue by Geevarghese** [CiscoDevNet/learning-labs-issues#77]
For the lab -Introduction to Meraki Integrations was not able to find the Scanning API under Network Wide > General  which is mentioned on the third page.
Here either we need to refer them to option 3 of the first page in the lab - Meraki Location Scanning API Python. Otherwise will get confused since that option is 
not available in the always on sandbox lab...
Also a suggestion to mention when using Sandbox lab use the Login to personal account option.

For the lab-  Meraki Dashboard API Using Postman all worked fine - Just a comment to check the name in the side menu alligned as in the heading of every page
Also In the How To Setup Your Own Computer - The command $pip install –r requirements.txt need to be mentioned. That is 6th point -Install the lab requirements.

For the lab- Meraki Location Scanning API Python  - Unable to do test since docker-compose command was not working on windows10.

For the lab - Meraki Wireless Health - All the postman labs worked as expected and no comments .

For the lab - 
Introduction to Meraki Webhook Alerts
The last page explanation is not clear... Need to rework on the steps...
[Learning-lab-Meraki.docx](https://github.com/CiscoDevNet/learning-labs-issues/files/2741156/Learning-lab-Meraki.docx)

**Comment by annegentle** [comment]
I believe a few items are still outstanding, such as the Webhook Alerts comments. Also, I believe that Cisco-imaged Windows10 machines cannot use Docker generally, so we'd have to test on the Win10 that we use for Cisco Live to see if it'll work. Maybe? 

Let's keep chipping away at these. 🐿

**Comment by denapom11** [comment]
Extremely out of date :)   closing
