### ISSUE TITLE
Extend block "How To Setup Your Own Computer" for PowerShell users on Windows

### ISSUE THREAD

**Issue by oborys** [CiscoDevNet/learning-labs-issues#79]
For PowerShell users on Windows add useful information in this part "Create a Python 3 virtual environment and activate it."
For example:
`# Windows PowerShell`
`py -3 -m venv venv`
`./venv/Scripts/activate`

Using git-bash for Windows it's hard to open code, that stored in git-bash directory, by IDE that installed on Windows dir. And use other Windows tools for code in git-bash directory

**Comment by annegentle** [comment]
This has been published - closing.
