### ISSUE TITLE
Introduction to Cisco DNA Center REST APIs module labs are missing code samples

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#81]
"How To Setup Your Own Computer" has the user clone https://github.com/CiscoDevNet/dnav3-code, however the repository is missing all the Python scripts referenced in the labs.

**Lab:** Execute Commands Across the Network with Cisco DNA Center Platform and Command Runner
https://learninglabs.cisco.com/modules/dnac-rest-apis/dnac-cmd-run/step/1
Missing files:
get_commands.py (referenced in "Step 2. Understand which commands can be run")
show_command.py (referenced in "Step 3. Run the first command(s)")

**Lab:** Quickly Deploy Configuration Templates with Cisco DNA Center Platform and Template Programmer
https://learninglabs.cisco.com/modules/dnac-rest-apis/dnac-template-prg/step/1
Missing files:
get_template.py (referenced in "Step 2. Projects and templates")
apply_template.py (referenced in "Step 3: Running a template")

**Comment by annegentle** [comment]
Thanks for reporting this! The files are in a PR that we need to merge. If you want it before merge, refer to https://github.com/CiscoDevNet/dnav3-code/pull/22/files -- and we should be able to merge today after testing.

**Comment by ntruncik** [comment]
Great, thanks Anne!

**Comment by ntruncik** [comment]
Code is there, thanks!
