### ISSUE TITLE
Introduction to Cisco SD-WAN REST APIs lab has screenshots missing

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#82]
The "Introduction to Cisco SD-WAN REST APIs" learning lab JSON screenshots on the last page ("Cisco SD-WAN REST API") are not clearly visible.
https://learninglabs.cisco.com/modules/sd-wan/intro-sd-wan-rest-api/step/4

Near the bottom...

"Please have a look at the DevNet always-on SD-WAN sandbox and explore the API by trying out some REST calls in the swagger interface. The username for the sandbox vManage is devnetuser and the password is Cisco123!. I suggest to try out the GET call for the /device endpoint that can be found under Monitoring - Device Details. The output for this call should be in JSON format and look like the one below:"

also...

"Another REST API endpoint that is useful and will retrieve all the devices monitoring details is /device/monitor found also under the Monitoring - Device Details category. The output for the /device/monitor endpoint should be similar to the one below:"

Both use the lab guide's ability to hide/show JSON output. This is not obvious at all, in fact, when I first opened this issue I thought it was missing.

The wording, format or colour of the "Click here to expand" text should be made visually more apparent that there is a code snippet hidden.

Perhaps even make it a button? Or at least change the font and center the text?

**Comment by bigevilbeard** [comment]
Investigating.. please standby.

**Comment by bigevilbeard** [comment]
I looked at that issue with the expanded code block, but anything fun is not rendering right and the image is a screen grab, which looks like its being poorly presented - the grab image is high quality, i think the size is messing the format

**Comment by ntruncik** [comment]
It's a minor thing, probably an ID ten T error on my side ;)

However from the way it was written it wasn't clear that I needed to click to expand the code block (or that there was even a code block to be expanded!)

What if instead of saying: "**Click to expand /device endpoint output**"
Rather, it said: "**Click HERE to expand and show expected /device endpoint output**"

Thoughts?

Thanks again!

**Comment by bigevilbeard** [comment]
Thanks @ntruncik perhaps i was looking for something more complex. I was hoping to get a dropdown bar in there (middle page) which was highlighted more. Formatting the text, does not seem to show any great results/if any. I am still looking, thanks for the suggestion. :)

**Comment by ntruncik** [comment]
If that visual menu bar is possible (and easy!) that would be even better.. however I'm a big fan of the K.I.S.S. principle :)

**Comment by bigevilbeard** [comment]
Good point! I made the changes per suggestion just now, i hope i caught all lines and fixed them. Thank you for contribution!
