### ISSUE TITLE
Building an IOx Application(iot-iox-app)-Broken link

### ISSUE THREAD

**Issue by vvaliapa** [CiscoDevNet/learning-labs-issues#83]
Hi Team,

In the "Building an IOx Application" learning lab, Page 1: ioxclient heading, link to download iox client is not pointing correctly.

Here is the learning lab link: 
https://developer.cisco.com/learning/lab/iot-iox-app/step/1

Kindly check.

**Comment by Reth11** [comment]
We can use the following link to download ioxclient.exe
https://pubhub.devnetcloud.com/media/iox/docs/artifacts/ioxclient/ioxclient-v1.7.2.1/ioxclient_1.7.2.1_windows_386.zip

**Comment by vvaliapa** [comment]
I have checked all the labs under "IOx - Cisco IoT Application Development" module, the link to download iox client is pointing correctly. Hence closing this issue.
