### ISSUE TITLE
Use Cisco IOX & Eximprod ES200 Virtual RTU to unlock the true power of your energy IoT data(iot-solutions-eximprod)-Broken link

### ISSUE THREAD

**Issue by vvaliapa** [CiscoDevNet/learning-labs-issues#84]
Hi Team,
In "Use Cisco IOX & Eximprod ES200 Virtual RTU to unlock the true power of your energy IoT data" learning lab, SCADA and Industrial Protocols page, DNP3 (Distributed Network Protocol) heading, "DNP Primer" link is not working.

Here is the learning lab link:
https://developer.cisco.com/learning/lab/iot-solutions-eximprod/step/4

Kindly check.

**Comment by Reth11** [comment]
I recommend using https://www.dnp.org/Resources/Public-Documents or https://www.dnp.org in place of the broken link. I'm not finding the originally referenced page.

**Comment by vvaliapa** [comment]
Issue is fixed now. 
Here is the link: https://developer.cisco.com/learning/lab/iot-solutions-eximprod/step/4
Closing this issue.
