### ISSUE TITLE
Deploy a Docker Application to Cisco Fog Director and IOx(iot-iox-fd-deploy)-screenshot updates and typos

### ISSUE THREAD

**Issue by vvaliapa** [CiscoDevNet/learning-labs-issues#86]
Hi Team,

In "Deploy a Docker Application to Cisco Fog Director and IOx" learning lab, found the following issues:
Here is the learning lab link:
https://developer.cisco.com/learning/modules/iox-basic/iot-iox-fd-deploy/step/9

1. Page 7, Publish the IOx Application heading, the second point "To publish your application, click the up-arrow just beneath it".  While testing I couldn't find "up-arrow" instead we have a "publish" button. We might need to change the screenshot also.
2. page 9, Test IOx Application, need to correct the typo "visiblee" in the second point.
3. In page 9, Hover your mouse pointer over the "AppIP" address and note the External IP address. while testing I couldn't find "AppIP" to find the external IP. I could find only the IP.

Attaching the screenshot.

![Docker](https://user-images.githubusercontent.com/41716353/54350241-e98c1a80-4672-11e9-9caa-b6d8d8066077.png)

Kindly check.

**Comment by smupad** [comment]
@klevenstein, FYI this Learning lab was made private as it requires updates - https://developer.cisco.com/learning/modules/iox-basic/iot-iox-fd-deploy/step/1.

**Comment by annegentle** [comment]
These have been updated; closing.
