### ISSUE TITLE
"SD-WAN automation with Ansible" learning lab Sandbox URL update needed

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#90]
"SD-WAN automation with Ansible" learning lab Sandbox URL update needed
https://developer.cisco.com/learning/modules/sd-wan/sdwan_automation_with_ansible/step/1

Page 2 - vManage REST APIs basics
Wrong URL for DevNet Sandbox:
"With the DevNet Sandbox, you can access **10.10.20.90:8443/apidocs**."
==> Should be **https://sandboxsdwan.cisco.com:8443/apidocs**

Page 4 - Create the Banner Feature Template
Wrong URL for DevNet Sandbox:
"Finally, let's verify on the vManage GUI that the template was indeed created. Go to **https://10.10.20.90:8443 (Username: admin / Password: admin)** Dashboard > Configuration > Templates and make sure Feature is selected."
==> Should be **https://sandboxsdwan.cisco.com:8443 (Username: devnetuser / Password: Cisco123!)**

**Comment by klevenstein** [comment]
Published, closing
