### ISSUE TITLE
DNAC Path Trace - print_token.py GitHub code needs updated

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#92]
The "End to End Visibility and Assurance with Path Trace and Cisco DNA Center Platform" learning lab uses code from https://github.com/CiscoDevNet/dnac-python-path-trace, of which one file (print_token.py) needs updated.

From the learning lab guide:
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-path-trace/step/4
Step 4: Set up a troubleshooting script
...has the user execute **$python print_token.py** and it should respond back with a token.
However, there is no output to the workstation CLI.

It seems the print_token.py file defines a function yet doesn't call it.

Adding the following line to the end of **print_token.py** gives the expected output :
`apic_login(apicem['host'], apicem['username'], apicem['password'])
`

Thanks!

**Comment by annegentle** [comment]
Nice catch - fixed in the Learning Lab, and tested in the code repo as well where I've asked @bigevilbeard to double-check my Python.

**Comment by annegentle** [comment]
Merged in code repo also, closing.

**Comment by ntruncik** [comment]
Awesome, thanks!!!
