### ISSUE TITLE
"Execute Commands Across the Network with Cisco DNA Center Platform and Command Runner" learning lab guide has a small typo.

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#93]
"Execute Commands Across the Network with Cisco DNA Center Platform and Command Runner" learning lab guide has a small typo.
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-cmd-run/step/2

**Step 2: Understand which commands can be run**
The script 'get_commands.py' uses this API call and then prints the result. The output is shown below:
```
**./get_templates.py** 
Exec commands supported:
[
    "call-home", 
    "cd", 
    "cping", 
    ...
```

Should read as the executed command `./get_commands.py`

**Comment by annegentle** [comment]
Thanks! Fixed.
