### ISSUE TITLE
"Quickly Deploy Configuration Templates with Cisco DNA Center Platform and Template Programmer" learning lab GitHub repo get_templates.py code issue

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#94]
Code cloned from https://github.com/CiscoDevNet/dnav3-code has an error.
(dnav3-code/intro-dnac/template-prg/get_templates.py)

**Step 2: Projects and templates**
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-template-prg/step/2

The lab guide says:
The script get_templates.py will make this API call, and display a formatted list of projects and templates.

```
./get_templates.py
Project:Sydney-Deployment
        ChangeDescription:3f7c91b4-4b17-4545-af58-290d51f1de55
        UpdateTZ:16e509e2-8791-4d29-981f-91cef4c953ff
```

This actually results in an error:
```
./get_templates.py 
  File "./get_templates.py", line 24
    if project['templates'] <> []:
                             ^
SyntaxError: invalid syntax
```

The get_templates.py file currently reads (lines 22-27):
 ```
22 # now print the templates
23     for project in response.json():
24         if project['templates'] <> []:
25             print('Project:{}'.format(project['name']))
26             for template in project['templates']:
27                 print ('\t{}:{}'.format(template['name'], template['id']))
```

And should be updated on line 24 to a valid operator, for example:
```
22  # now print the templates
23     for project in response.json():
24         if project['templates'] >= []:
25             print('Project:{}'.format(project['name']))
26             for template in project['templates']:
27                 print ('\t{}:{}'.format(template['name'], template['id']))
```

**Comment by annegentle** [comment]
I went ahead and changed this, though I'm running Python 2.7.15 and got no complaints on syntax with the `<>` remaining. So I'm kind of curious about your syntax checker or maybe Python version? Either way, thanks so much for testing and reporting errors.

**Comment by ntruncik** [comment]
Hi Anne,

I was using Python 3, as the "How to Setup Your Computer" section recommends. It's very possible this is why I saw the issue and you didn't with Python 2.

That said - sometimes it really is just user error on my side :)  Would it be possible to re-test using Python 3?

Thanks!

**Comment by annegentle** [comment]
Yep, sure enough, that's it, I get the syntax error on Python 3. The change is in there now, thanks for helping me learn more!

**Comment by ntruncik** [comment]
My pleasure! I'm learning too so it was a great opportunity for me to dig deeper :)

**Comment by ntruncik** [comment]
P.S. doesn't look like the change has been merged into the Master quite yet: https://github.com/CiscoDevNet/dnav3-code/blob/master/intro-dnac/template-prg/get_templates.py
