### ISSUE TITLE
"Quickly Deploy Configuration Templates with Cisco DNA Center Platform and Template Programmer" learning lab GitHub repo get_template.py code issue

### ISSUE THREAD

**Issue by ntruncik** [CiscoDevNet/learning-labs-issues#95]
Code cloned from https://github.com/CiscoDevNet/dnav3-code has an error.
(dnav3-code/intro-dnac/template-prg/get_template.py)

**Step 2: Projects and templates**
https://developer.cisco.com/learning/modules/dnac-rest-apis/dnac-template-prg/step/2

The lab guide says:
The script get_template.py will return the all of the versions of a template.

```
./get_template.py
Project:Sydney-Deployment Template:ChangeDescription

Ver|  templateId for version of template Time of commit
1  |b22388de-e2ee-4786-bbb2-5192a79e73f2 2018-05-28:14:45:10
2  |de533a13-67b0-4ffe-b9c6-e107f484da52 2018-05-28:14:45:41
3  |ea105b86-1857-49b1-86dd-e06051a9b489 2018-05-28:16:46:42 fixed typo in interfce
4  |1baa7cb1-43af-4e1e-a91b-942856d7e3ec 2018-05-28:16:49:41
```

This actually results in an error:
```
./get_template.py 
Traceback (most recent call last):
  File "./get_template.py", line 21, in <module>
    response.raise_for_status()
  File "/Users/ntruncik/coding/dnav3-code/myvenv/lib/python3.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Server Error for url: https://sandboxdnac.cisco.com:443/api/v1/template-programmer/template/version/2f6ad7a2-8eb2-4a9f-a4ec-444ddecca122

```
It appears that the hard-coded template ID on Line 17 of get_template.py is the culprit. When I change the hard-coded value for a template ID that is valid, then get_template.py executes OK.

One solution could be to accept a user variable into the script (for the template ID) on the command line using the output of the previous step in the lab guide (when we ran get_templates.py). If so, then both the code on GitHub and the learning lab guide would need updated with these instructions.

**Comment by annegentle** [comment]
Hi, want to see what you think of this input solution: https://github.com/CiscoDevNet/dnav3-code/pull/58

**Comment by ntruncik** [comment]
Hi Anne!

Thanks for your quick replies and testing!

I tested the new code and functionally it works well - taking the Template ID as user input greatly enhances the flexibility of the script.

**raw_input** is Python 2 specific so **input** is needed for Python 3 (also mentioned in #58 referenced above)

**Comment by ntruncik** [comment]
Thanks for merging this change into the code and making it Python 3 friendly... all good now!
